hazelcast/hazelcast-simulator

dist/src/main/dist/conf/stabilizer.properties
pom.xml
stabilizer/pom.xml
stabilizer/src/main/java/com/hazelcast/stabilizer/Utils.java
stabilizer/src/main/java/com/hazelcast/stabilizer/common/StabilizerProperties.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/HazelcastJars.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/Provisioner.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/ProvisionerCli.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/git/BuildSupport.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/git/GitRepository.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/git/GitSupport.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/git/HazelcastFilenameFilter.java
stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/git/HazelcastJARFinder.java
stabilizer/src/test/java/com/hazelcast/stabilizer/provisioner/git/BuildSupportTest.java
stabilizer/src/test/java/com/hazelcast/stabilizer/provisioner/git/HazelcastFilenameFilterTest.java

Hazelcast GIT revision can be specified via the HAZELCAST_VERSION_SPEC in stabilizer.properties.
```
HAZELCAST_VERSION_SPEC=git=f0288f713
HAZELCAST_VERSION_SPEC=git=myRepo/myBranch
HAZELCAST_VERSION_SPEC=git=v3.2.3
```
--git option can used to enforce a specific Hazelcast version via command line. It overrides the HAZELCAST_VERSION_SPEC property. It's a convenient way to enforce Hazelcast version from shell scripts.
```
provisioner --restart --git f0288f713
or
provisioner --restart --git myRepo/myBranch
```
Stabilizer will always fetch the main Hazelcast repository https://github.com/hazelcast/hazelcast.git. Name of this repository is always 'origin'.
Additional repositories can be specified via the GIT_CUSTOM_REPOSITORIES property in stabilizer.properties
``` …
```

#284 - GIT Support

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/TestContainer.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/utils/AnnotationFilter.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/utils/ReflectionUtils.java
stabilizer/src/test/java/com/hazelcast/stabilizer/worker/TestContainerTest.java

Removed warnings from `TestContainer`. Enhanced `findMethod()` to search super classes for annotations, so we can use inheritance at all in test classes (e.g. to create a base class for `IntIntMapTest`, `StringMapTest` and follow up classes like `StringByteMapTest` etc.).

Enhancement and cleanup of TestContainer

---

stabilizer/src/main/java/com/hazelcast/stabilizer/agent/workerjvm/WorkerJvmLauncher.java
stabilizer/src/main/java/com/hazelcast/stabilizer/coordinator/Coordinator.java

- added uploadResourcesToWorkers() to Coordinator but it has not spec file on CoordinatorCli.
-  Firstly user must upload resources file to **/hazelcast-stabilizer/dist/src/main/dist/resources**  at his/her local working directory.

Renewed resources upload feature

---

update-stabilizer

Just a small change which is laying around on my PC for a long time.
I don't insist on the version line, but the use of `$STABILIZER_HOME` is definitely a nice thing on your local machine.

Enhance update stabilizer script

---

dist/src/main/dist/tests/slow/slow-operation-map.properties
stabilizer/src/main/java/com/hazelcast/stabilizer/utils/ReflectionUtils.java
tests/src/main/java/com/hazelcast/stabilizer/tests/slow/SlowOperationMapTest.java

Added SlowOperationMapTest to trigger slow operation logs in Hazelcast 3.5 or newer. This test is a fulfillment for the `Hogging Partition Thread` feature for Hazelcast 3.5.
Here is a sample worker.log from a successful run:
https://gist.github.com/Donnerbart/20cc7c6b77e252c567f5
If you run the test with an older version (or rather a version without the `SlowOperationDetector`) the test will through an assert: `java.lang.AssertionError: This test needs Hazelcast 3.5 or newer`

Added SlowOperationMapTest

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/selector/OperationSelectorBuilder.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapTransactionReadWriteTest.java

Fixed off-by-one error in `OperationSelectorBuilder` during population of array (index started at 1 instead of 0).
Fixed cleanup of `MapTransactionReadWriteTest` (one selector per thread, removed warnings).

Fixed NPE during tests with OperationSelectorBuilder

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractWorkerTask.java

Adjusted performanceUpdateFrequency in AbstractWorkerTask. Added a setter to overwrite the value in a test class without the need of a runtime property via test.properties.

Adjusted performanceUpdateFrequency in AbstractWorkerTask

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractWorkerTask.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AsyncAbstractWorkerTask.java
stabilizer/src/test/java/com/hazelcast/stabilizer/worker/TestContainerTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/IntIntMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapAsyncOpsTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/StringStringMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/slow/SlowOperationMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/syntheticmap/StringStringSyntheticMapTest.java

* Cleanup of `MapAsyncOpsTest`
* Introducing optional `beforeRun()` and `afterRun()` method for `AbstractWorkerTask`
* Renamed some methods and added documentation.

Cleanup of MapAsyncOpsTest && beforeRun() and afterRun() for AbstractWorkerTask

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractAsyncWorkerTask.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractMonotonicWorkerTask.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractWorkerTask.java
stabilizer/src/test/java/com/hazelcast/stabilizer/worker/TestContainerTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/IntIntMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapAsyncOpsTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapCasTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/StringStringMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/slow/SlowOperationMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/syntheticmap/StringStringSyntheticMapTest.java

* Cleanup of `MapCasTest`
* Introducing `AbstractMonotonicWorkerTask` for worker tasks which will not use an `OperationSelector`
This PR depends on #517 (it won't even compile without those changes).

Cleanup of MapCasTest && AbstractMonotonicWorkerTask

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/TestContainer.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractWorkerTask.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapEntryListenerTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/helpers/EntryListenerImpl.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/helpers/EventCount.java

* Cleanup of `MapEntryListenerTest`
* Introducing the method `AbstractWorkerTask.afterCompletion()` which is executed once after all workers are done

Cleanup of MapEntryListenerTest

---

dist/src/main/dist/conf/hazelcast.xml
dist/src/main/dist/stabilizer-tests/test.properties
stabilizer/src/main/java/com/hazelcast/stabilizer/test/utils/TestUtils.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapMaxSizeTest.java

* Checked the actual `MaxSizeConfig` during setup phase (fail fast).
* Retrieved the max size per node from configuration (to get rid of the hard coded `1000` in the test).
* Also removed the `@Verify(global = false)` method (config is printed in the setup method now).
* Changed the configuration map name from `MaxSizeMap` to `MapMaxSize`, so it matches the test name automatically.
* Added the `assertEqualsStringFormat` method from `HazelcastTestSupport` to create verbose assert messages more easily (was used during refactoring, will be useful for other tests).

Cleanup of MapMaxSizeTest

---

stabilizer/src/main/java/com/hazelcast/stabilizer/agent/Agent.java
stabilizer/src/main/java/com/hazelcast/stabilizer/agent/HarakiriMonitor.java
stabilizer/src/main/java/com/hazelcast/stabilizer/agent/remoting/AgentRemoteService.java
stabilizer/src/main/java/com/hazelcast/stabilizer/common/messaging/MessagesFactory.java
stabilizer/src/main/java/com/hazelcast/stabilizer/communicator/Communicator.java
tests/src/main/java/com/hazelcast/stabilizer/tests/concurrent/lock/LockConflictTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/concurrent/lock/SimpleLockTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/executor/ExecutorTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/icache/EntryProcessorICacheTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapEntryProcessorTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapHeapHogTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapPredicateTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapStoreTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapTimeToLiveTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapTransactionContextConflictTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapTransactionContextTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapTransactionTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/SplitClusterDataTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/queue/QueueTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/queue/TxnQueueWithLockTest.java

Cleanup and possible bug in Hazelcast 3.5 due to new config pattern matcher (configs may not get fetched with full class identifier, but simple class name).

Cleanup of Class.getName() method calls

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/TestContainer.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractAsyncWorker.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractMonotonicWorker.java
stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractWorker.java
stabilizer/src/test/java/com/hazelcast/stabilizer/worker/TestContainerTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/IntIntMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapAsyncOpsTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapCasTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapEntryListenerTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapEntryProcessorTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapLockTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapLongPerformanceTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapMaxSizeTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapPredicateTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapRaceTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapReduceTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/StringStringMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/slow/SlowOperationMapTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/syntheticmap/StringStringSyntheticMapTest.java

Renamed `AbstractWorkerTask` to `AbstractWorker`, same for child classes. Renamed forgotten `BaseWorkerTask` named methods, variables and tests.

Renamed AbstractWorkerTask to AbstractWorker

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/AgentCli.java
simulator/src/main/java/com/hazelcast/simulator/agent/remoting/AgentRemoteService.java
simulator/src/main/java/com/hazelcast/simulator/common/AgentAddress.java
simulator/src/main/java/com/hazelcast/simulator/common/AgentsFile.java
simulator/src/main/java/com/hazelcast/simulator/communicator/Communicator.java
simulator/src/main/java/com/hazelcast/simulator/communicator/CommunicatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/AwsProvisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/AwsProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/CloudInfo.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/CloudInfoCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java

* Added bind address for Agent.
* Used bind address in AgentSmokeTest.
* Found better place for 'agents.txt' constant.
* Unified format of command line parser classes.
* Got rid of some System.exit() calls.

AgentSmokeTest work out of the box

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceMonitor.java

Performance count per agent was fetched and always overwritten. But the overwritten value was just from the first worker and not summed up (like the total value).
Layout:
```
INFO  17:06:04 Total number of agents: 2
INFO  17:06:04 Total number of Hazelcast member workers: 4
INFO  17:06:04 Total number of Hazelcast client workers: 0
INFO  17:06:04     Agent 172.16.16.206 members: 2 clients: 0
INFO  17:06:04     Agent 172.16.16.209 members: 2 clients: 0
```
Before:
```
INFO  17:07:28 Total performance    100.00%         596,803 ops       19,893.43 ops/s
Agent 172.16.16.209   24.38%         145,488 ops        4,849.60 ops/s
Agent 172.16.16.206   25.00%         149,187 ops        4,972.90 ops/s
```
After:
```
INFO  17:00:32 Total performance      100.00%         575,700 ops       19,190.00 …
```

Fixed total performance count in PerformanceMonitor

---

tests/src/main/java/com/hazelcast/simulator/tests/map/unbound/AbstractMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/unbound/MapLatencyTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/unbound/MapResultSizeLimitTest.java

`MapResultSizeLimitTest` performs `IMap.values()` etc. on a map filled slightly over the result size limit and checks the number of thrown exceptions.
`MapLatencyTest` performs `IMap.values()` etc. on a map filled slightly below the result size limit to create latency probe results (and checks that no exceptions are thrown).

Created tests for unbound return values feature.

---

checkstyle/suppressions.xml
simulator/src/main/java/com/hazelcast/simulator/utils/AnnotationReflectionUtils.java
simulator/src/main/java/com/hazelcast/simulator/utils/BindException.java
simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/test/java/com/hazelcast/simulator/utils/AnnotationFilterTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/AnnotationReflectionUtilsTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupportTest.java

* Increased code coverage of `AnnotationFilter`, `AnnotationReflectionUtils` and `PropertyBindingSupport`.
* Suppressed method name checks for test classes (was too annoying)
I'm not completely done with `PropertyBindingSupport` yet, but this should already be a noticeable improvement to merge.
```
com.hazelcast.simulator.utils	10% (2/20)	6% (10/149)		9% (79/846)
com.hazelcast.simulator.utils	40% (8/20)	27% (41/148)	23% (197/844)
```
(it's a bit hard to measure since we still have the package `com.hazelcast.simulator.utils` twice in the project)

Increased code coverage of some util classes

---

probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionResult.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbeTest.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/utils/DataSetUtils.java

* Fixed HDR Probe measurement.
* Fixed HDR Probe combine.
* Fixed HDR Probe histogram creation.
* Fixed Latency Probe histogram creation.
HDR probe measurements were in milliseconds not microseconds. The combine didn't copy one of the histogram's content. The accuracy buttons for HDR probe were not implemented in Visualizer yet. The Latency Probe had an issue with aggregating big numbers in Visualizer.

Fixed HDR Probe

---

simulator/src/main/java/com/hazelcast/simulator/worker/tasks/IWorker.java
tests/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticRequest.java
tests/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticTest.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/GetOperation.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/PutOperation.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/StringStringSyntheticMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/SyntheticMap.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/SyntheticMapProxy.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/SyntheticMapService.java

* Fixed compilation issue with Hazelcast 3.5
* Fixed dropped future in async mode of SyntheticTest if syncFrequency > 1
* Made usage of IWorker to get rid of ThreadSpawner and atomic operation counter in SyntheticTest
* Cleanup of SyntheticTest and StringStringSyntheticMapTest> to increase checkstyle compliance
* Improved JavaDoc of IWorker

Fixed SyntheticTest to compile with Hazelcast 3.5 (and other fixes + cleanup)

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java

Fixing #402
A member can actually report NULL as its output - it's perfectly fine - just imagine you have more agents than configured test members.

Confusing message removed.

---

dist/pom.xml
dist/src/main/config/build-distribution-archive.xml

There is no content in the JAR of the dist module, all files are determined in the maven assembly configuration. So it's not an error that it can't be included, it's not necessary.

Fixed warning during build of missing dist jar.

---

tests/src/main/java/com/hazelcast/simulator/tests/map/SqlPredicateTest.java

It yields the same result, but it's much faster
as just a single worker push the initial data.

SqlPredicateTest has a global warm-up

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorHelper.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/test/TestCase.java
simulator/src/main/java/com/hazelcast/simulator/test/TestRunner.java
simulator/src/main/java/com/hazelcast/simulator/test/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessor.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunTestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/test/TestRunnerTest.java
simulator/src/test/java/com/hazelcast/simulator/tests/PropertiesTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupportTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/TestContainerTest.java

* Improved `TestRunner` to set properties in test object
* Cleanup of `TestCase` (Visibility Modifier issue from Sonar)
* Increased code coverage of `TestContainer`
We can now pass properties to a test via `TestRunner` to be a bit more flexible in developing and debugging tests.
All changed code is covered by tests, beside the small change in `WorkerCommandRequestProcessor`.

Improved TestRunner to set properties in test object

---

dist/src/main/dist/tests/atomiclong/asyncatomiclong.properties
dist/src/main/dist/tests/atomiclong/atomiclong.properties
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractAsyncWorker.java
tests/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AsyncAtomicLongTest.java
tests/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AtomicLongTest.java

* Fixed verify methods in `AtomicLongTest` and `AsyncAtomicLongTest` for multiple workers
* Fixed `AsyncAtomicLongTest` for client usage
* Used configurable `Metronome` instead of `sleepSeconds()`
* Made usage of new `IWorker` API
* Improved API of `AbstractAsyncWorker`

Fixed AtomicLongTest and AsyncAtomicLongTest to work with multiple workers

---

pom.xml

In the https://github.com/hazelcast/hazelcast-ee-simulator-tests we are using 2.1.4 version so 2.0.1 version in the simulator causes some contradiction.

Changed HdrHistogram version

---

simulator/src/main/java/com/hazelcast/simulator/common/GitInfo.java
simulator/src/test/java/com/hazelcast/simulator/common/GitInfoTest.java

Fixes #629. The output is now as expected "Unknown" and not a NPE:
```
INFO  17:14:39 Hazelcast Simulator Provisioner
INFO  17:14:39 Version: 0.5, Commit: Unknown, Build Time: Unknown
INFO  17:14:39 SIMULATOR_HOME: /home/donnerbart/bin/hazelcast-simulator
WARN  17:14:39 /home/donnerbart/bin/simulator.properties is not found, relying on defaults
```
Increased code coverage to test this case. Also tried it by compiling without git repo and run the `Provisioner` afterwards.

Fixed NPE in GitInfo

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AsyncMapStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/MapStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/MapStreamerFactory.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/SyncMapStreamer.java
simulator/src/test/java/com/hazelcast/simulator/worker/loadsupport/AsyncMapStreamerTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/loadsupport/MapStreamerFactoryTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/loadsupport/SyncMapStreamerTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/IntByteMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/MapLongPerformanceTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/MapPredicateTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/SqlPredicateTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/StringStringMapTest.java
utils/src/main/java/com/hazelcast/simulator/utils/VersionUtils.java
utils/src/test/java/com/hazelcast/simulator/utils/VersionUtilsTest.java

Fixes #630. Created a factory to get a sync or async `MapStreamer` implementation, depending on the Hazelcast version.
I didn't touch the `AsyncMapStreamer`, should work as before. The `SyncMapStreamer` is new but very simple. Started to write tests for both classes, but the async one is not at 100% coverage yet.
Please double-check if I did the version compare thing in the correct way, otherwise we'll have the async implementation in the old Hazelcast versions!

Fix MapStreamer issue with Hazelcast versions prior 3.5

---

simulator/src/main/java/com/hazelcast/simulator/common/GitInfo.java

Fixed new SonarQube complain in `GitInfo`:
> Dodgy - Load of known null value
>
>The variable referenced at this point is known to be null due to an earlier check against null. Although this is valid, it might be a mistake (perhaps you intended to refer to a different variable, or perhaps the earlier check to see if the variable is null should have been a check to see if it was nonnull).
Code should look a bit nicer now, tests are still green, SonarQube should be happy.

Fixed SonarQube complain in GitInfo

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/remoting/AgentsClient.java
simulator/src/main/java/com/hazelcast/simulator/test/TestPhase.java
simulator/src/main/java/com/hazelcast/simulator/test/TestRunner.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/commands/GenericCommand.java
simulator/src/main/java/com/hazelcast/simulator/worker/commands/IsPhaseCompletedCommand.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/agent/CommandFutureTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunTestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/TestContainerTest.java

Introduced an `Enum` for the test phases instead of using Strings which invoke method via reflection on the worker side.
Also changes the behavior of the `IsPhaseCompletedCommand` to be more strict, e.g. when asking for complection of a phase, which is not running at the moment. Same is for the start of a new phase, if the old phase is not yet done.

Cleanup of test phase handling

---

pom.xml
simulator/src/main/java/com/hazelcast/simulator/communicator/CommunicatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

* Update of dependency and plugin versions.
* Adapted code to new JOpt API.
The JOpt update needed a little code adjustment. A bit hidden is the update of the Maven Compiler plugin from 3.0 to 3.3 as well as Maven Surefire plugin from 2.10 to 2.18.1.
@Danny-Hazelcast: Could the update of the amazonaws dependency be problematic?

Update of dependency and plugin versions

---

pom.xml
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessor.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/tests/FailingTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessorTest.java

Increased line coverage of WorkerCommandRequestProcessor to 87%.
I did this because we had some changes in this class the other day with 0% code coverage. Had a very bad feeling about this, since the behavior was changed in case of out-of-order executions of test phases (new exceptions are thrown).
Forgive me the usage of PowerMockito. I didn't want to get rid of `ExceptionUtil.report()`, but needed a way to check the reported exceptions.

Increased line coverage of WorkerCommandRequestProcessor

---

tests/src/main/java/com/hazelcast/simulator/tests/topic/ReliableTopicTest.java

Test is failing continuously with these are AssertionError. Relation btw expectedCount and actualCount is directly proportional with listenerPerTopic.
```
listenerPerTopic = 1
cause=java.lang.AssertionError: published messages don't match received messages expected:<0> but was:<151278060> 
```
```
listenerPerTopic = 2
cause=java.lang.AssertionError: published messages don't match received messages expected:<125045179> but was:<250090358>
```
```
listenerPerTopic = 3
cause=java.lang.AssertionError: published messages don't match received messages expected:<98494500> but was:<295483500>
```
Xml like this:
```
<reliable-topic name="relaibleTopic*">
<statistics-enabled>true</statistics-enabled>
<message-listeners>
<message-listener>com.hazelcast.simulator.tests.topic.ReliableTopicTest.StressMe …
```

[Don't Merge] ReliableTopic test

---

tests/src/main/java/com/hazelcast/simulator/tests/helpers/HazelcastTestUtils.java
tests/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticTest.java
tests/src/main/java/com/hazelcast/simulator/tests/syntheticmap/SyntheticMapProxy.java

Without this change Simulator is failing to run with Hazelcast 3.4 when compiled against Hazelcast 3.5

Fallback for a binary incompatible change in Hazelcast Internals

---

tests/src/main/java/com/hazelcast/simulator/tests/icache/MangleICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/helpers/ICacheOperationCounter.java

Test was chosen because of:
```
MangleICacheTest.java:101:9: Cyclomatic Complexity is 23 (max allowed is 12).
MangleICacheTest.java:101:9: Method length is 91 lines (max allowed is 60).
MangleICacheTest.java:101:9: NPath Complexity is 434 (max allowed is 50).
MangleICacheTest.java:109:17: switch without "default" clause.
MangleICacheTest.java:110:50: Avoid nested blocks.
MangleICacheTest.java:122:48: Avoid nested blocks.
MangleICacheTest.java:133:47: Avoid nested blocks.
MangleICacheTest.java:144:40: Avoid nested blocks.
MangleICacheTest.java:158:39: Avoid nested blocks.
MangleICacheTest.java:174:41: Avoid nested blocks.
MangleICacheTest.java:188:31: Avoid nested blocks.
```

Cleanup of MangleICacheTest.

---

dist/src/main/dist/simulator-tests/test.properties
dist/src/main/dist/tests/map/map-time-to-live.properties
tests/src/main/java/com/hazelcast/simulator/tests/map/MapTimeToLiveTest.java

Test was chosen because of:
```
MapTimeToLiveTest.java:93:33: Inner assignments should be avoided.
MapTimeToLiveTest.java:98:40: Inner assignments should be avoided.
MapTimeToLiveTest.java:103:40: Inner assignments should be avoided.
MapTimeToLiveTest.java:106:40: Inner assignments should be avoided.
MapTimeToLiveTest.java:109:40: Inner assignments should be avoided.
MapTimeToLiveTest.java:114:65: Must have at least one statement.
```

Cleanup MapTimeToLiveTest.

---

tests/src/main/java/com/hazelcast/simulator/tests/icache/AddRemoveListenerICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/ListenerICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/helpers/ICacheEntryEventFilter.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/helpers/ICacheEntryListener.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/helpers/ICacheListenerOperationCounter.java

Test was chosen because of:
```
AddRemoveListenerICacheTest.java:111:29: Inner assignments should be avoided.
AddRemoveListenerICacheTest.java:118:36: Inner assignments should be avoided.
AddRemoveListenerICacheTest.java:122:36: Inner assignments should be avoided.
AddRemoveListenerICacheTest.java:125:36: Inner assignments should be avoided.
```

Cleanup of AddRemoveListenerICacheTest.

---

probes/src/main/java/com/hazelcast/simulator/probes/probes/IntervalProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/AbstractIntervalProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/AbstractSimpleProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/DisabledProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/LatencyDistributionProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/MaxLatencyProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/WorkerProbe.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/DisabledProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/LatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/MaxLatencyProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/OperationsPerSecProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/WorkerProbeTest.java

Added `recordValue(long latencyNanos)` to probes to ease latency measurements in asynchronous setups.

Added recordValue(long latencyNanos) to probes

---

dist/src/main/dist/tests/external/externalclientresponsetest.properties
dist/src/main/dist/tests/external/externalclienttest.properties
tests/src/main/java/com/hazelcast/simulator/tests/external/ExternalClientResponseTest.java
tests/src/main/java/com/hazelcast/simulator/tests/external/ExternalClientTest.java

I made a run with a simple testsuite and duration=0 to wait for all tests to finish:
```
ExternalClientTest@class = com.hazelcast.simulator.tests.external.ExternalClientTest
ExternalClientTest@waitForClientsCount = 2
ExternalClientTest@waitIntervalSeconds = 5
ExternalClient1@class = com.hazelcast.simulator.tests.external.ExternalClientResponseTest
ExternalClient1@delaySeconds = 15
ExternalClient2@class = com.hazelcast.simulator.tests.external.ExternalClientResponseTest
ExternalClient2@delaySeconds = 30
```
worker.log
```
INFO  2015-06-19 10:44:20,311 [Thread-11] com.hazelcast.simulator.tests.external.ExternalClientResponseTest: Client response sent!
INFO  2015-06-19 10:44:35,307 [Thread-12] com.hazelcast.simulator.tests.external.ExternalClientResponseTest: Client response sent!
INFO …
```

Added tests for external clients

---

probes/src/main/java/com/hazelcast/simulator/probes/probes/IntervalProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/SimpleProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/AbstractIntervalProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/AbstractSimpleProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/DisabledProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/OperationsPerSecProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/WorkerProbe.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/DisabledProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/LatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/MaxLatencyProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/OperationsPerSecProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/WorkerProbeTest.java
tests/src/main/java/com/hazelcast/simulator/tests/external/ExternalClientTest.java

Added method `setValues(durationMs, invocations)` to `SimpleProbe`.
This will be used to record throughput values from external clients, which measure the raw values by themselves, but have no probes implementation.

Added method setValues(durationMs, invocations) to SimpleProbe

---

probes/src/main/java/com/hazelcast/simulator/probes/probes/ProbesResultXmlReader.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/utils/DataSetUtils.java

* Fixed reading of multiple probes in a single file in `ProbesResultXmlReader`.
* Removed debug message of unsupported probe types.

Fixed ProbesResultXmlReader

---

probes/src/main/java/com/hazelcast/simulator/probes/probes/SimpleProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/AbstractIntervalProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/AbstractSimpleProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/DisabledProbe.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/DisabledProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/LatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/MaxLatencyProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/OperationsPerSecProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/WorkerProbeTest.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContainer.java
tests/src/main/java/com/hazelcast/simulator/tests/external/ExternalClientTest.java

Added disable methods to probes to enable collection of probes from a single test instance in the cluster. Before the `getResult()` may have thrown an exception if there is no data in the probes of all other instances.

Added disable methods to probes

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunTestSuiteTest.java

Added an optional synchronization for test phases between parallel running tests. This is very useful if you have to coordinate actions between tests, which is e.g. needed when using external clients. The actual workaround is to manually sync the tests via `ICountDownLatch` or `IAtomicLong`, which is a lot of work and still racy.
The default behavior should not be changed, despite the setup phase, which will be the only phase which is synchronized by default. This should not significantly influence any of our test runs, since the setup phase should not run for a long time (we have the warmup phases for long running operations).
TLDR: All parallel running tests will now wait until all setup phases are done. Other phases can be synced optionally.

Optional synchronization for test phases

---

simulator/src/main/java/com/hazelcast/simulator/agent/workerjvm/WorkerJvmSettings.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/commands/RunCommand.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessorTest.java

Made passive mode for members configurable via `simulator.properties`. Per default it is still enabled, but you can switch it off now to have a run phase on the member side, even if there are clients on the same node!

Made passive member mode configurable.

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/HarakiriMonitor.java
simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/TemplateBuilder.java
simulator/src/main/java/com/hazelcast/simulator/utils/CloudProviderUtils.java
simulator/src/test/java/com/hazelcast/simulator/common/SimulatorPropertiesTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/CloudProviderUtilsTest.java

* Added `CloudProviderUtils` to have all String comparisons of CLOUD_PROVIDER in a single place.
* Replaced `exitOnError()` with proper use of `CommandLineExitException`.
* Minimal cleanup of `HarakiriMonitor`.

Cleanup of CLOUD_PROVIDER detection

---

tests/src/main/java/com/hazelcast/simulator/tests/helpers/KeyUtils.java

If client instance,then getlocal member doesn't return null but throws
UnsupportedOperationException.

Fixes issue with KeyUtils and client

---

dist/src/main/dist/conf/hazelcast.xml
dist/src/main/dist/tests/map/mapstoreevict.properties
tests/src/main/java/com/hazelcast/simulator/tests/map/MapEvictAndStoreTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/helpers/MapStoreWithCounterPerKey.java

Test for duplicate store when eviction happens and MapStore is slow (see hazelcast/issues/4448).

Added MapEvictAndStoreTest

---

simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessor.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupportTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/TestContainerTest.java

1. Probe configuration via properties does not use the `probe-` prefix anymore.
2. Fail-fast behaviour re-introduced - there is a fast failure when unknown property is configured.
3. I did remove the option to inject probes via Setup method. It's not used in practice and it just adds complexity.

Probe configuration improvements

---

simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupportTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_bindProperty_NonNumericalTest.java

* Fixed wrong equals value for `SimpleProbe` in `PropertyBindingSupport`.
* Fixed cyclomatic complexity in `PropertyBindingSupport`.
* Cleanup of `PropertyBindingSupport`.
* Cleanup of tests for `PropertyBindingSupport`.

Fixed issues in PropertyBindingSupport

---

simulator/src/main/java/com/hazelcast/simulator/utils/ThrottlingLogger.java
simulator/src/test/java/com/hazelcast/simulator/utils/ThrottlingLoggerTest.java

It's useful when you want to log something, but not more often than every X ms.

ThrottlingLogger added

---

simulator/src/main/java/com/hazelcast/simulator/agent/CommandFuture.java
simulator/src/test/java/com/hazelcast/simulator/agent/CommandFutureTest.java

Fixed possible `wait(0)` if `CommandFuture` was used with timeout values under one millisecond.
Kudos to @jerrinot who found this issue in my Simulator Protocol PR.

Fixed infinite wait() in CommandFuture

---

tests/src/main/java/com/hazelcast/simulator/tests/ExampleTest.java

Verification was fragile as the test is probabilistic
and chances are there are no entries created for some keys.

Vefification in the ExampleTest fixed

---

simulator/src/main/java/com/hazelcast/simulator/protocol/connector/WorkerConnector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/ResponseType.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/CreateTestOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/IntegrationTestOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/OperationType.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/OperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/TestOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContextImpl.java
simulator/src/test/java/com/hazelcast/simulator/protocol/ProtocolIntegrationTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/ProtocolUtil.java
simulator/src/test/java/com/hazelcast/simulator/protocol/operation/OperationTypeTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/TestOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessorTest.java

Initial migration of `WorkerCommandRequestProcessor` to `WorkerOperationProcessor` (`InitCommand` to `CreateTestOperation`).

Initial migration of WorkerCommandRequestProcessor

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/MapStreamerFactory.java

MapStreamerFactory works even when BuildInfo class is unavailable

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceMonitor.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/commands/GetPerformanceStateCommand.java
simulator/src/main/java/com/hazelcast/simulator/worker/commands/PerformanceState.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceTracker.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerCommandRequestProcessorTest.java

Fixes #724
Throughput is now calculated on workers instead of Coordinator.
Latency between "Obtaining stats on a worker" and "Processed on Coordinator" does not play a role anymore.

Calculate Throughput on Workers instead on Coordinator

---

dist/src/main/dist/bin/harakiri-monitor
dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/simulator-tests/run.sh
simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/HarakiriMonitor.java
simulator/src/main/java/com/hazelcast/simulator/agent/HarakiriMonitorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorHelper.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/utils/CloudProviderUtils.java
simulator/src/test/java/com/hazelcast/simulator/agent/HarakiriMonitorTest.java
utils/src/main/java/com/hazelcast/simulator/utils/CliUtils.java

* Moved start/kill Agents functionality to Coordinator.
* Removed start Agents functionality from `--restart` and renamed the CLI command to `--install`.
* Renamed `--listAgents` to `--list`.
* General cleanup of Provisioner CLI commands texts.
```
user@system:~$ provisioner --help
INFO  12:14:01 Hazelcast Simulator Provisioner
INFO  12:14:01 Version: 0.6-SNAPSHOT, Commit: 0aaf2da, Build Time: 01.09.2015 @ 12:04:55 CEST
INFO  12:14:01 SIMULATOR_HOME: /home/donnerbart/bin/hazelcast-simulator
Option                         Description                                                                  
------                         -----------                                                                  
--clean                        Cleans the remote Worker directories on the …
```

Start/stop Agents in Coordinator instead of Provisioner

---

dist/src/main/dist/conf/hazelcast.xml
tests/src/main/java/com/hazelcast/simulator/tests/icache/AddRemoveListenerICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/BatchingICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/CasICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/CreateDestroyICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/EntryProcessorICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/ExpiryICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/ExpiryTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/ListenerICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/MangleICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/PerformanceICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/ReadWriteICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/StringICacheTest.java

fix for https://github.com/hazelcast/hazelcast-enterprise/issues/468
when you use `getCache`, it first tries to find cache config. If there is not created cache it gets cache config from xml and creates a proxy. If there is no config even in the xml, it throws exception. So in our case, if cache is not created yet, it pulls the config from xml with `NATIVE` in-memory format. But when you use `createCache`, it uses its own config by sending this config to whole cluster and then creates a proxy. So in our case, since default `CacheConfig` instance is created, `BINARY` in-memory format is used. So I mean, there may be inconsistent state in the cluster due to this behaviour.  Therefore, it may be better using `getCache` always since we have cache config in our xml and getting rid of all …

ICache from xml

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java

Fixed broken fail fast mechanism by aborting the run phase of all tests after a single test failure.
**Note:** This will not prevent to start all other test phases, it will just abort the run phase. This should already shorten the testsuite execution massively if there is a test failure. If we want to skip all other test phases after a failure happened, we need more code changes :)

Fixed fail fast mechanism to abort testsuite after failure

---

dist/src/main/dist/simulator-tests/test.properties
tests/src/main/java/com/hazelcast/simulator/tests/replicatedmap/ReplicatedMapTest.java

so with a 500 ro 10000 clients, number of key stored in cluster is diffrent.
change to operate on a global key domain where number of keys to be put is well defined.
importent for EE HD test, not to force evection from the global pool and fail other test.  also
the meta data pool of HD grows with number of map/cache entires.  so a fixed number is
easyer to handle.  with EE HD test using large number of clients

replicated map test inserts keys per  member / client running the test.

---

tests/src/main/java/com/hazelcast/simulator/tests/concurrent/lock/LockTest.java

The totalMoney variable should not be updated inside the test as this is the initial value of money which is then used as an 'expected' value.
Tested on Hazelcast Simulator v0.6.

Fixed test failure in LockTest.

---

simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractAsyncWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractMonotonicWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/IWorker.java
tests/src/main/java/com/hazelcast/simulator/tests/map/SerializationStrategyTest.java

All lifecycle methods like before/after etc are allowed to throw checked exceptions.
Exception handling is taken care of at a single place: AbstractWorker. Instead of repeated
on different places.

Simplified exception handling

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AbstractAsyncStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AsyncCacheStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AsyncMapStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/StreamerFactory.java

https://github.com/hazelcast/hazelcast-simulator/issues/809
- added new constructor which includes *concurrencyLevel* to AbstractAsyncStreamer 
- added new **getInstance** methods to StreamFactory so we can easily create streamer with defined concurrency level
easily change via **test.properties**
```
public int streamerConcurrencyLevel = 2500;
...
Streamer<String, String> streamer = StreamerFactory.getInstance(map,streamerConcurrencyLevel);
```

fix attempt for #809 

---

simulator/src/main/java/com/hazelcast/simulator/probes/Probe.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/ThroughputProbe.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitor.java
simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java
simulator/src/test/java/com/hazelcast/simulator/probes/impl/ThroughputProbeTest.java

Resetting is not a concern of the probe. If a delta needs to be stored
compared to the previous run, it needs to be done somewhere else.
The driver behind this change is that we want to create thread unsafe
probes for higher performance. And resetting from an arbitrary thread
is undesirable.

The probe.getIntervalCountAndReset is replaced by a get

---

simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractAsyncWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractMonotonicWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractMonotonicWorkerWithProbeControl.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractWorkerWithProbeControl.java
simulator/src/main/java/com/hazelcast/simulator/worker/tasks/VeryAbstractWorker.java

The location was inappropriate because some worker classes take care of
their own probes.

Moved probe out of veryabstractworker

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RemoteClient.java
simulator/src/main/java/com/hazelcast/simulator/protocol/connector/AbstractServerConnector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/connector/AgentConnector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/connector/WorkerConnector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/CreateWorkerOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessor.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RemoteClientTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/connector/AbstractServerConnectorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/operation/OperationCodecTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/TestOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessorTest.java

This will prevent duplicate connections being created. Normally the io balancer will take care of it; but I'm chasing a performance variation and I want to exclude certain causes.

Configurable startup delay workers

---

simulator/src/main/java/com/hazelcast/simulator/protocol/processors/TestOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/IntegrationTestWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/MemberWorker.java
simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitor.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/TestCaseRunnerTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/TestOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/IntegrationTestWorkerTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/MemberWorkerTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitorTest.java

Lots of unwanted complexity
WorkerTask didn't get shut down due to races
It can happen that not all results are send to the coordinator and some operation information gets lost. This issue has been resolved as well.

Cleanup of WorkerPerformanceMonitor

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Uploader.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/UploaderTest.java

It doesn't upload to the Coordinator, but from the Coordinator. Normally names are created
about the target system, not about the using system.

Renamed CoordinatorUploader to Uploader.

---

dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/conf/worker.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerjvm/WorkerJvmLauncher.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerjvm/WorkerJvmSettings.java
simulator/src/main/java/com/hazelcast/simulator/cluster/AgentWorkerLayout.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/WorkerParameters.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerType.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/WorkerParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/operation/OperationCodecTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessorTest.java

The worker script that gets generated, is now pulled out as template. This gives one full control on e.g. the java command to execute, profilers, and all kinds of other things like checking e.g. the power governor.
Just copy the SIMULATOR_HOME/conf/worker.sh to the working directory and start modification.

Pulled out worker script

---

simulator/src/main/java/com/hazelcast/simulator/test/TestContext.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AsyncAtomicLongTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AtomicLongTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/ExtractorMapTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/PutAsyncAndThenTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/special/FailingTest.java
tests/tests-hz36/src/main/java/com/hazelcast/simulator/tests/map/PutAsyncAndThenTest.java

TargetInstance can be acquired using @InjectTargetInstance annotation.
This reduces coupling with the HZ framework. Makes it easier in the future for
other imdg's to be added under simulator.

Deprecated TestContext.getTargetInstance

---

DummyTestRunnerid.java
simulator/src/main/java/com/hazelcast/simulator/test/PropertyBinding.java
simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/test/java/com/hazelcast/simulator/test/AbstractTestContainerTest.java
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_NestedPropertyBindingTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_Test.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_nestedPropertiesTest.java
utils/src/main/java/com/hazelcast/simulator/utils/ReflectionUtils.java
utils/src/test/java/com/hazelcast/simulator/utils/ReflectionUtilsTest.java

Also add a new feature that an object graph can be reconstructed is added.
So imagine you have class Person with a null arm, then you can define
'arm.finger.nail.length=10'
and the whole object graph is being recreated. 
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/939

Fixes nested propertybinding issues

---

simulator/src/main/java/com/hazelcast/simulator/common/SPMCLongArrayQueue.java
simulator/src/test/java/com/hazelcast/simulator/common/SPMCLongArrayQueueTest.java

Used in Hot Restart test for throughput control and will possibly be generalized to work with `Metronome`.

Lock-free single-producer/multiple-consumer array queue of longs

---

simulator/src/main/java/com/hazelcast/simulator/probes/Probe.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/EmptyProbe.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_RunTest.java

The Probe interface is about recording values; not retrieving the content.

Removed Probe.get method

---

simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceLogWriter.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitor.java

The performance.csv now using epoch time. Time in millis is converted to seconds,
but millis are allowed to be expressed using a double.
This is comparable with e.g. dstats output

Using epoch time on performance.csv

---

simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java

Removed the `worker-` prefix for directory names to cleanup the redundant naming schema.

Removed the worker- prefix for directory names

---

archetype/src/main/resources/archetype-resources/workdir/run.sh
dist/src/main/dist/conf/after-completion.sh
dist/src/main/dist/conf/worker.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureContainer.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/HdrHistogramContainer.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/FailureContainerTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/HdrHistogramContainerTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/TestCaseRunnerTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/ProtocolUtil.java
simulator/src/test/java/com/hazelcast/simulator/protocol/connector/CoordinatorConnectorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessorTest.java
utils/src/main/java/com/hazelcast/simulator/utils/FileUtils.java

The output directory for all artifacts for a testsuite run are now downloaded in a new directory in the working directory. This directory will have some timestamp by default, but by setting the testsuite id, the directory name is also determined.
There is also an automatic download of the worker directories of the remote machine for that given testsuite-id.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/887
Another closely related feature is added. There is now a script which gets executed after the coordinator has completes running the testsuite and the artifacts are downloaded. This script will do whatever is needed, e.g. creating hgrm based on hdr files. If a file with the name 'after-completion.sh' s added to the working dir, one can fully control what is happening.

Configurable output directory

---

simulator/src/main/java/com/hazelcast/simulator/test/CompositeCallable.java
simulator/src/main/java/com/hazelcast/simulator/test/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/utils/AnnotatedMethodRetriever.java
simulator/src/test/java/com/hazelcast/simulator/utils/AnnotatedMethodRetrieverTest.java

Now  you can make e.g. multiple @Teardown methods, or have them on the super.
This goes for most annotations like setup, teardown, verify etc.
This aligns with @Before/@After from junit
fixes https://github.com/hazelcast/hazelcast-simulator/issues/915

Dealing with super classes and annotation

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/test/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/test/TestContextImpl.java
simulator/src/main/java/com/hazelcast/simulator/test/TestPhase.java
simulator/src/main/java/com/hazelcast/simulator/test/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/test/annotations/AfterWarmup.java
simulator/src/main/java/com/hazelcast/simulator/utils/AnnotationFilter.java
simulator/src/main/java/com/hazelcast/simulator/worker/PrimordialRunStrategy.java
simulator/src/main/java/com/hazelcast/simulator/worker/RunStrategy.java
simulator/src/main/java/com/hazelcast/simulator/worker/RunWithWorkersRunStrategy.java
simulator/src/main/java/com/hazelcast/simulator/worker/TimeStepRunStrategy.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/TestCaseRunnerTest.java
simulator/src/test/java/com/hazelcast/simulator/test/AbstractTestContainerTest.java
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_RunTest.java
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_TimeStepTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/TimeStepRunStrategyIntegrationTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitorTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AtomicLongTest.java

Instead of having a 'warmup' method which needs to trigger the logic that needs to be benchmark, the actual timestep methods are going to be used for the warmup.
So in the warmup phase the threads are created, thread contexts are created and the timestep methods are called in exactly the same was as in the run phase.
Once the warmup phase has completed, the 'reset' method is called which allows for any global state to be reset.
In the run phase new threads/thread-context is created (so we don't need to reset these).
The big advantage of this approach is that one can now configure  a warmup duration and that the warmup logic is a lot simpler. If you don't care about resetting state, then no code change needs to be made.
The warmup is configured using
```
coordinator --warmupDuration 1m …
```

Introduced propper warmup

---

simulator/src/main/java/com/hazelcast/simulator/test/PropertyBinding.java
simulator/src/main/java/com/hazelcast/simulator/test/TestContext.java
simulator/src/main/java/com/hazelcast/simulator/test/TestContextImpl.java

We have @InjectHazelcastInstance. The goal of this removal is to make
simulator less provider dependent.
This method was already deprecated in 0.8

TestContext.getHazelcastInstance removed

---

dist/src/main/dist/bin/benchmark-report
simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStateContainer.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceState.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/PerformanceStateContainerTest.java
simulator/src/test/java/com/hazelcast/simulator/probes/ProbeTestUtils.java
simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/performance/PerformanceStateTest.java

The HDRProbe measures in microseconds (so it convers nanos to micro's). But this makes tooling like the HistogramLogProcessor not intuitive to use.
So the Recorder in the HDRProbe now stores the measured data in nanos, but it is configured that it can drop nano second detail.

HDR TimeUnit fix

---

simulator/src/main/java/com/hazelcast/simulator/utils/Bash.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/helpers/ComplexDomainObject.java
utils/src/main/java/com/hazelcast/simulator/utils/BashCommand.java
utils/src/main/java/com/hazelcast/simulator/utils/NativeUtils.java
utils/src/main/java/com/hazelcast/simulator/utils/helper/ExitException.java
utils/src/main/java/com/hazelcast/simulator/utils/helper/ExitStatusOneException.java
utils/src/main/java/com/hazelcast/simulator/utils/helper/ExitStatusZeroException.java
utils/src/test/java/com/hazelcast/simulator/utils/BashCommandTest.java

Instead of ending up with a huge set of overloaded execute methods in
the NativeUtils, a more builder like approach is used.
This change is needed for pulling out the hazelcast installation into a bash script.

Introduced BashCommand

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

If file named worker.sh is in the working dir, it is selected otherwise
go to the simulator_home. No need to add another switch.

Removed the switch to set a worker script

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

The option to place a file to override an existing configuration remains. But no
specific flags to point to a different file than the on in the current working
directory.
Another step for multivendor support.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/1019

Removed hz config switches coordinator cli

---

dist/src/main/dist/conf/install-hazelcast-enterprise.sh
dist/src/main/dist/conf/install-hazelcast.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java

```
INFO  12:19:42 Installing 'hazelcast' 'outofthebox' on Agents using /home/david/bin/hazelcast-simulator/conf/install-hazelcast.sh
ERROR 12:19:42 Failed to execute [/home/david/bin/hazelcast-simulator/conf/install-hazelcast.sh 2016-08-09__12_19_42  outofthebox]
ERROR 12:19:42 Aborting, invalid VERSION_SPEC 
```
Public IPs are empty in local mode, so the variables in the bash script get shifted the `$version_spec` is empty. Since the `VERSION_SPEC` is always set, the easy is solution is to swap the order of the parameters.
Seems to work flawless after the fix:
```
INFO  12:40:50 Installing 'hazelcast' 'outofthebox' on Agents using /home/david/bin/hazelcast-simulator/conf/install-hazelcast.sh
INFO  12:40:50 Successfully installed 'hazelcast'
```

Fixed install script in local mode

---

dist/src/main/dist/conf/worker-hazelcast-enterprise.sh
dist/src/main/dist/conf/worker-hazelcast.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessSettings.java

All hz specifics are in the worker-hazelcast scripts.
A small improvement is that the worker directory now contains the hazelcast.xml being used; instead of it being written
in /tmp and linked to the worker.
More cleanup is needed; e.g. worker process setting still has hard hz links

Worker process settings hz agnostic

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/RemoteClient.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RemoteClientTest.java

The remote client should just forward 'operations' to the right boxes. It should not be
involved with any simulator specific logic

Moved init testsuite to RunTestSuiteTask

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RemoteClient.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/ComponentRegistry.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java

* Fixed restart of Workers after failure (was missing termination of Workers and cleanup of `ComponentRegistry`)
* Renamed `TestCaseRunnerTest` to `RunTestSuiteTaskTest`, which is what test is actually doing now
* Refactored `RunTestSuiteTaskTest` to directly use `RunTestSuiteTask` inst of `Coordinator`

Fixed restart of Workers after critical failure. Refactored TestCaseRunnerTest.

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/FailureSender.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/FailureSenderImpl.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessFailureMonitor.java
simulator/src/test/java/com/hazelcast/simulator/agent/workerprocess/FailureSenderImplTest.java
simulator/src/test/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessFailureMonitorTest.java

Pulled out `FailureSender` to decouple `WorkerProcessFailureMonitor` from `Agent` and `AgentConnector`

Pulled out FailureSender interface

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureContainer.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureListener.java
simulator/src/main/java/com/hazelcast/simulator/protocol/connector/CoordinatorConnector.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/FailureContainerTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/ProtocolUtil.java
simulator/src/test/java/com/hazelcast/simulator/protocol/connector/CoordinatorConnectorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessorTest.java

Removed component registry as argument. ComponentRegistry is now updated
through a regular listener registration. This reduces coupling.

Simplified FailureContainer

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/StartWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/AgentWorkerLayout.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/DeploymentPlan.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/StartWorkersTaskTest.java

so it just receives a list of workersettings per agent. This reduces coupling on the DeploymentPlan and extended internals.

Simplified StartWorkersTask

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/DeploymentPlan.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RemoteClientTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/StartWorkersTaskTest.java

* Cleanup of unused tests methods.
* Added asserts to StartWorkersTaskTest.
* Changed DeploymentPlan.createSingleInstancePlan() to directly return the map of worker settings.

Cleanup of RemoteClientTest and StartWorkersTaskTest

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java

This is needed for the session based approach since many testsuites can be executed with a single coordinator instance.

Removed testsuite from Coordinator constructor

---

simulator/src/main/java/com/hazelcast/simulator/common/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java

run specific properties are moved into the TestSuite. This is needed for
the session functionality so that multiple test suites can be run with
different settings.

Moved properties into TestSuite

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestPhaseListeners.java
simulator/src/test/java/com/hazelcast/simulator/TestSupport.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/TestPhaseListenersTest.java

Currently it isn't a problem because will kill the coordinator after running
a testsuite; but the TestPhaseListeners are not unregistered. This causes
problems with the session based approach.

Fixes memory leak in RunTestSuiteTask

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/WorkerParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/AgentWorkerLayout.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/WorkerParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/deployment/DeploymentUtilsTest.java

Simplified to a single field for tracking performance monitor interval
removed dependency on simulatorproperties (needed for coordinator sessions)

WorkerParameter cleanup performanceMonitorInterval

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/FailureHandlerImpl.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/FailureHandler.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcess.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessFailureMonitor.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessManager.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/test/java/com/hazelcast/simulator/agent/FailureHandlerImplTest.java
simulator/src/test/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessFailureMonitorTest.java

fix #1123
It has been improved so that the worker isn't deleted and follows the regular process
of termination in case of failure. But if a worker has been marked as 'ignore failure'
on the agent, the failure isn't published to the coordinator.
This means that its connections and all that are closed when the worker is terminated
and no communication with a dead worker is scheduled.

Fixes problem that testcase not stopping

---

dist/src/main/dist/conf/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/test/annotations/AfterRun.java
simulator/src/main/java/com/hazelcast/simulator/test/annotations/BeforeRun.java
simulator/src/main/java/com/hazelcast/simulator/test/annotations/TimeStep.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepModel.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunStrategy.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunner.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunnerCodeGenerator.java
simulator/src/main/resources/TimeStepRunner.ftl
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TimeStepModel_IllegalTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TimeStepModel_probabilityTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/queue/ProducerConsumerTest.java

Allows for more complex timestep models with different groups of threads execute different timestep methods. 
Example:
```
@Timestep(group="producer")
void produce(){
queue.offer("");
}
@Timestep(group="consumer")
void consume(){
queue.take();
}
configure with:
producerThreadCount=2
consumerThreadCount=4
```

Execution Group for timestep

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/utils/CommonUtils.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/special/IterationTest.java

Removed the stop thread. 
Removed waitForTestCaseSpec since you always want to do this. You never want to move on to the next phase, if run/warmup has not yet completed since this would immediately run into exceptions like the one from the ticket.
fix https://github.com/hazelcast/hazelcast-simulator/issues/1198

Testcaserunner phase cleanup

---

simulator/src/main/java/com/hazelcast/simulator/protocol/connector/AgentConnector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/ResponseFuture.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/ResponseFutureListener.java
simulator/src/main/java/com/hazelcast/simulator/protocol/handler/ForwardToWorkerHandler.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessor.java
simulator/src/test/java/com/hazelcast/simulator/protocol/handler/ForwardToWorkerHandlerTest.java

Blocking in the ForwardToWorkerHandler leads to hogging threads waiting for a response. It is now solved asynchronously using a listenable future. 
It doesn't address the actual reduction of the number of threads. But it will make sure we need less of them.
Probably this could be done directly in netty itself, but I don't have the time to figure that part out.

Nonblocking futures in netty

---

dist/src/main/dist/conf/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollector.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceStats.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollectorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessorTest.java

1: simplification by getting rid of the queue.
2: sometimes no interval performance info is shown; this is because there is nothing in the queue. Now there always is a latest
3: monitor performance is enabled by default fix #1158
4: each test shows its own performance information fix #1231

Performance collector cleanup

---

simulator/src/main/java/com/hazelcast/simulator/common/AgentsFile.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/ConfigFileTemplate.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRunMonolith.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/StartWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/RcWorkerStartOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/AgentData.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/ComponentRegistry.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/WorkerData.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/WorkerQuery.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/utils/HazelcastUtils.java
simulator/src/main/java/com/hazelcast/simulator/utils/TagUtils.java
simulator/src/test/java/com/hazelcast/simulator/TestSupport.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/common/AgentsFileTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunMonolithTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/tasks/StartWorkersTaskTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/registry/WorkerQueryTest.java
simulator/src/test/java/com/hazelcast/simulator/provisioner/ProvisionerCliTest.java
simulator/src/test/java/com/hazelcast/simulator/provisioner/ProvisionerTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/HazelcastUtilsTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/TagUtilsTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/MemberWorkerTest.java

For more advanced configuration, tags are added as an ability to:
- query for specific members e.g. run test on cluster1.
- pass key/value pairs for customization in e.g. config files
fix #1228 
fix #1229 
fix #1247

Tags for workers/agents

---

simulator/src/main/java/com/hazelcast/simulator/utils/TestUtils.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunnerCodeGenerator.java

Instead of dumping in the main worker directory, the artifacts (classes/java-src) are now
dumped in a subdirectory timestep-worker-classes.
Fix #1271

Timestep artifacts in subdir

---

simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_bind0_NumericalTest.java

e.g. 10_000_000 vs 10000000
fixes #1285

Added underscore support for large numbers for property binding

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

fix #1300
fix #1301 
The old option still work; but you get a log warning. In Simulator 0.11 they will be removed probably.

Renaming of clientMemberVmOption and workerVmOption

---

dist/src/main/dist/conf/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ComputeServiceBuilder.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/wizard/Wizard.java
simulator/src/main/java/com/hazelcast/simulator/wizard/WizardCli.java
simulator/src/test/java/com/hazelcast/simulator/common/SimulatorPropertiesTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/HarakiriMonitorUtilsTest.java
simulator/src/test/java/com/hazelcast/simulator/wizard/WizardTest.java

The variables can be defined and exported in the bash script and will automatically
be picked up without needing to create a file.
Also there is no more need to create an ec2.identity and ec2.credential file. If
the properties refer to a file; the file is loaded. Otherwise the properties will
be interpreted as a direct value.
fix https://github.com/hazelcast/hazelcast-simulator/issues/1305

Remove simulator properties requirement

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestSuite.java
simulator/src/test/java/com/hazelcast/simulator/common/TestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java

So coordinator can still be used with a test.properties file; but can also be used
with a string containing the tests.

Removed the need for test.properties file

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestSuite.java
simulator/src/test/java/com/hazelcast/simulator/common/TestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java

So if no explicit test file passed to coordinator, look for test.properties in working dir
fixes #1314

Defaults to test.properties if exist

---

archetype/src/main/resources/archetype-resources/workdir/run.sh
archetype/src/main/resources/archetype-resources/workdir/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java

Using the upload directory, any artifact needed like jars, will automatically be put
on the classpath. So extra jars needed, we can just copy in the upload directory. No
need to have a special flag for it.
This flag was still in the system, but not used any longer.

Removed the worker classpath option

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollector.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java

The problem was that the desired running time was used, not the actual running time.
So if you run for 10 seconds and then end the test, but your desired running time is 60 seconds, and the throughput is 1/6 of real throughput.

Fixes a bug in the performance calculation premature ending

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/ReflectionAsyncMapStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/StreamerFactory.java

This can happen when Simulator was compiled against Hazelacast 3.7+,
but Hazelcast 3.6- is used in runtime
The `IMap::fooAsync` returns `ICompletableFuture` in Hazelcast 3.7, but it returns just a regular `Future` in Hazelcast 3.6 and older. 
There are bridge methods so code compiled against Hazelcast 3.6 will work when Hazelcast 3.7 is used in runtime. However code compiled against Hazelcast 3.7+ will not work when Hazelcast 3.6- is used in runtime and it affects Simulator Streamers. 
This changeset detects this situation and fallbacks to reflection-based streamers - method return type does not matter in reflective invocations.

Map Streamer fallback to reflection when putAsync() throws NoSuchMethodError

---

simulator/src/main/java/com/hazelcast/simulator/utils/GeneratorUtils.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/StringStringMapTest.java

the original property still works and it's used as a default

StringStringMapTest can use variable value length

---

simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

This is because the agents are written after everything completes. But it
should be written before the simulator/java installation begins.

Fix #1396 agent file missing simulator/java failed instances

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/TerminateWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
simulator/src/main/java/com/hazelcast/simulator/worker/operations/TerminateWorkerOperation.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceMonitor.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/performance/PerformanceMonitorTest.java

Instead of it having a parameter with the delay for members; the coordinator
takes care of delaying any termination to member if there are clients. This
makes implementation less complex.
Also some renaming.

Simplified the TerminateWorkerOperation

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessManager.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/registry/AgentData.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/registry/ComponentRegistry.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/registry/TestData.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/AddressLevel.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/SimulatorAddress.java
simulator/src/test/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessFailureMonitorTest.java
simulator/src/test/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessManagerTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/FailureCollectorTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollectorTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/operations/FailureOperationTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/registry/AgentDataTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/registry/ComponentRegistryTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/registry/WorkerQueryTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/core/AddressLevelTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/core/SimulatorAddressTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerTest.java

Tests  addressing isn't needed. The coordinator decided which workers are going to get a requests and tests worker addressing is lowest level of addressing needed. Inside the worker it is just a test id.
fix #1418

Removed Test Address level since not used

---

tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/MangleICacheTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/helpers/CacheUtils.java

Previously `CacheUtils.createCacheManager` was using internal API which could result in issues which do not reflect normal JCache usage.
Obtaining a `CacheManager` via JCache API for the default `URI` & `ClassLoader` will always return the same `CacheManager` instance, so in order to (mostly) preserve this method's "create" semantics, randomization was added in the URI used to get-or-create the `CacheManager`.

Obtain CachingProvider & CacheManager via JCache API

---

simulator/src/main/java/com/hazelcast/simulator/worker/WorkerOperationProcessor.java

The exception was not reported due to only catching exceptions; not all
throwables.

CreateTest class not found error

---

tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/MangleICacheTest.java

Invoking CachingProvider.close in a timestep method will close the CachingProvider, its CacheManagers and their Caches. Since there can be no separate CachingProvider per test, this timestep will interfere with other `Cache` tests.

Remove CachingProvider.close timestep from MangleICacheTest

---

dist/src/main/dist/bin/coordinator

Otherwise, when printing performance numbers to stdout under a different encoding (like `ANSI_X3.4-1968` in my case)  __?__ can be seen instead of  __&#181;__
Example:
` 1,007,825 ops   100,651.65 ops/s         45 ? (avg)        155 ? (99.9th)     11,239 ? (max)`

Set coordinator file encoding to UTF8

---

simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java
simulator/src/main/java/com/hazelcast/simulator/wizard/Wizard.java
simulator/src/main/java/com/hazelcast/simulator/wizard/WizardUtils.java

After running `simulator-wizard --createWorkDir tests`, content of `run` file is like this:
```
/home/ahmet/simulator/file:/home/ahmet/simulator/hazelcast-simulator-0.10-SNAPSHOT/lib/simulator-0.10-SNAPSHOT.jar!/runScript
```
Instead of file path, `run` file should be a copy of `runScript`.  This pr fixes that problem by copying actual content of `runScript` to `run` file.
Additionally order of parameters for`copyResourceFile` method is changed to make it easier to read.

Fixed resource file convertion to text

---

dist/src/main/dist/conf/prepare_session.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/PrepareSessionTask.java

The problem was that the old session directory on the remote machines wasn't deleted and
therefor the old files were causing problems.
fix #1584

Fix problem with multiple runs and same sesion id

---

dist/src/main/dist/conf/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerParameters.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessManager.java
simulator/src/main/java/com/hazelcast/simulator/utils/NativeUtils.java
simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerTest.java

The worker check if the agent is still alive. This is done by adding the
agent.pid to the worker parameters and the worker periodically checking if
the agent is still running.

Fixes orphan worker problem

---

dist/src/main/dist/conf/agent_start.sh
simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/AgentCli.java
simulator/src/main/java/com/hazelcast/simulator/common/ProcessSuicideThread.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/AgentUtils.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunMonolithTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java

Agents/workers can keep dangling if the coordinator process is killed. This is
especially a problem if the process is run from the IDE.
To solve this problem the agent had the pid of the parent process (for local
setups) and the workers the pid of their agent. If they see that the parent process
is offline by using this parent pid, they terminate themselves.
fix #1598

Fixes orphan process problem

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/StartWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/TerminateWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/protocol/CoordinatorClient.java

Since the agent info is available locally anyway, no need to pass it as argument.

Cleanup in call to CoordinatorClient.invokeAll(agents,..)

---

dist/src/main/dist/conf/record_timestamp.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/RunTestSuiteTask.java

Creates a new file containing the timestamps on the remote machine
a test started/stopped.
This feature is needed to deal with proper warmup/cooldown and aligning
dstats data with the benchmark run.

Timestamp recording

---

README.md
dist/src/main/dist/conf/provisioner-log4j.xml
dist/src/main/dist/conf/simulator.properties
pom.xml

JClouds was ripped out some time ago, but there were still some
references to jclouds. These have been removed in this PR.

Removed remaining references to jclouds

---

simulator/src/main/java/com/hazelcast/simulator/utils/NativeUtils.java

The problem is a bug in the IBM JVM that isn't too happy
when a method exists, that isn't called, in a class. And this
method is pointing to classes that don't exist.
Fix: the explicit casting to sun.management.VMManagement has been
removed. Fix has been verified with IBM 6.

Fixes problem IBM 6/7

---

dist/src/main/dist/conf/install-simulator.sh

The `tests` directory is not part of the distribution anymore.

Removed a directory upload from install-simulator.sh

---

README.md

The `worker-kill`, compared to `worker-script`, has the `command` option argument.

Added --command option to worker-kill examples in README.md

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AbstractAsyncStreamer.java

Sometimes initial inserting is taking longer, but it's still making progress before the tests, but hitting this timeout. I guess we don't need any parameter for this (at least now), but it should unblock me with 3.10 testing.

Increate timeout for streamers

---

dist/src/main/dist/conf/client-hazelcast.xml
dist/src/main/dist/conf/hazelcast.xml
simulator/src/main/java/com/hazelcast/simulator/vendors/HazelcastDriver.java

Instead of letting the driver automagically add the log4j hazelcast
logging property, it is now configured in the hazelcast xml.
The reason behind this is that we want to control the logging being used
e.g turn logging off due to overhead.

Fixes logging for HZ instances

---

simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceLogWriter.java

For some locales a comma is used as decimal seperator leading
to problems in csv files.

Fixes problem in performance.cvs.

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/map/LongByteArrayMapTest.java

Cleanup; values byte array isn't regenerated in prepare which is not needed. Since it is already done in setup.

LongByteArrayMapTest cleanup

---

dist/src/main/dist/conf/benchmark-report.py
dist/src/main/dist/conf/hdr.sh
simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java
simulator/src/main/java/com/hazelcast/simulator/utils/PerformanceCsv.java

Performance csv that is result of comparison:
```
"session","benchmark","10%","20%","50%","75%","90%","95%","99%","99.9%","99.99%","max","operations","duration","throughput"
hazelcast,LongStringCacheTest-get,245.759,261.631,307.711,338.943,373.759,395.263,446.463,587.263,4012.031,23789.567,74054815,178023,41598.45357060605
ignite,LongStringCacheTest-get,379.391,423.935,524.799,627.711,749.055,840.191,1065.983,1507.327,6094.847,31424.511,41661865,178033,23401.20370942466
```
Having a csv makes it a lot easier to process results compared to graphs.

Added performance.csv that is generated when comparing benchmarks

---

dist/src/main/dist/conf/aws-ec2_terminate.sh
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

The issue was that private ip addresses were used and when there are
multiple vpc of a single user in the same region, there is no guarantee
that ip addresses are unique.
So sometimes based on private ip's the wrong machine id's were found.
This is fixed by making use of public ip address for lookup.

Fixed problem scaling down

---

dist/pom.xml
dist/src/main/config/build-distribution-archive.xml
drivers/driver-hazelcast4/pom.xml
drivers/driver-infinispan9/pom.xml
drivers/pom.xml
pom.xml

Also fixes problem with infinispan 9. Sohow when the infinispan10
driver is included, the infinispan 10 dependencies get add to
the infinispan9 driver. So for the time being the infinspan10 driver
has been deactivated.

Added thread affinity libraries

---

dist/src/main/dist/conf/prepare_session.sh

Without these changes, the ssh command never returns and simulator hangs before starting the benchmark.

Fix starting dstat remotely

---

README.md
simulator/src/main/resources/testSuite

* Fixes a bunch of typos in the readme
* Replaces `IntIntMapTest` (which doesn't exist) with `IntByteMapTest` in readme and sample properties
* Also updates year and links in the copyright notice

Fix typos in readme

---

dist/src/main/dist/conf/download.sh

Simulator runs can produce large amount of data such as diagnostics, JVM
and other logs, JFR, perf and other recordings. Downloading these files
over VPN can be slow. Since typically the network bandwidth is the
bottleneck not the CPU, rsync compression is hardwired for downloading
benchmark results from the remote boxes. Uploading and installing
simulator doesn't need to compress since these phases deal with small
or compressed files.

Make rsync compressing the test results during download

---

simulator/src/main/java/com/hazelcast/simulator/test/annotations/TimeStep.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/MetronomeSupplier.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunStrategy.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunner.java
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/MetronomeSupplierTest.java

Added support for rampup so that threads get added to the test over time. Example usage.
```
class=yourtest
threadCount=10
rampupSeconds=60
```
For this test, every 6 seconds a thread is added so that after 60 seconds there are 10 threads running.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/1805

Added support for rampup

---

dist/src/main/dist/conf/simulator.properties

I used the wrong property name in the documentation:
VERSION=zulu8.12.0.1-jdk8.0.71-linux_x64.tar.gz
Instead of 
JDK_VERSION=zulu8.12.0.1-jdk8.0.71-linux_x64.tar.gz

Minor documentation fix

---

dist/src/main/dist/conf/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

The shared simulator.properties can sometimes be a problem if you need to
test with different settings e.g. version_spec.
So the version spec can now be configured fromt the coordinator.
--version maven=4.0.1
This feature is backwards compatible, so no compatibility problems.
Also added some additional examples to the JDK urls

Version spec from coordinator

---

simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java

So instead of setting the instance type on the simulator.properties, it can be
set when calling coordinator scale.
coordinator --scale 5 --instanceType c5.9xlarge

Instance type cli option

---

drivers/driver-ignite2/src/main/java/com/hazelcast/simulator/ignite2/cache/LongStringCacheTest.java

The size of the value isn't respected.

LongStringCache for ignite has a bug

---

dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/jdk-install/jdk-oracle-11-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-13-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-8-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-9-64.sh
dist/src/main/dist/jdk-install/jdk-support.sh

This can be done through the JDK_URL, no need for duplication.

Removed oracle JDK install scripts.

---

dist/src/main/dist/conf/worker-log4j.xml
dist/src/main/dist/jdk-install/jdk-support.sh

Removed the functions to install the different flavors of Java. Can
now be done through the JDK_URL.
Also minor worker-log4j.xml cleanup.

Removed jdk bash functions

---

drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/tests/map/IntByteMapTest.java
drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java
drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/tests/map/LongStringMapTest.java
drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/utils/KeyLocality.java
drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/utils/KeyUtils.java
drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java
drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/tests/map/LongStringMapTest.java
drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/tests/map/MapTxTest.java

Out-of-the-box test support to easily compare hz 3 and 4 versions. Having same tests for driver3 and driver4 makes life easier.

Synchronize tests folders between driver3 and driver4

---

pom.xml

In the current state, if you run `mvn clean install -DskipTests`, the drivers won't get included in the `dist/target/<name>.zip` because the dist module gets executed *before* the drivers are built, therefore the JARs won't get included. 
This will result in errors like: `FATAL 17:39:44 Could not locate driver class [com.hazelcast.simulator.hazelcast4.Hazelcast4Driver]`
This PR fixes this by moving the `dist` module in the `<modules>` list to the end as according to the official Maven documentation  ( https://maven.apache.org/guides/mini/guide-multiple-modules.html):
```
a project dependency on another module in the build
a plugin declaration where the plugin is another module in the build
a plugin dependency on another module in the build
a build extension declaration on another module …
```

Fix distribution to include the drivers JARs

---

dist/src/main/dist/conf/benchmark-report.py

Terminal link will be clickable.

make printed report file link clickable

---

.gitignore
drivers/driver-hazelcast3/conf/install-hazelcast-support3.sh
drivers/driver-hazelcast4/conf/install-hazelcast-support4.sh
simulator/src/main/java/com/hazelcast/simulator/wizard/Wizard.java
simulator/src/main/java/com/hazelcast/simulator/wizard/WizardUtils.java
simulator/src/main/resources/example-client-config.xml
simulator/src/main/resources/example-member-config.xml
simulator/src/main/resources/runScript

This PR tries to simplify the onboarding of new users to Simulator. Namely:
* Fix running tests locally for Hazelcast 3 and 4 - the change needed is in the `install-hazelcast-support*.sh` scripts. The JARs weren't properly copied to the classpath of the workers.
* Often the first problem everybody faces when starting with Simulator is that they don't know where to put member config, where to put client config, what are the simple coordinator parameters etc. I added those example configs. Therefore, in order to get your first Simulator test running, you only need to do `simulator-wizard --createWorkDir tests` and then ./tests/run

Fix local runs + enhanced the getting started experience with example configuration

---

dist/src/main/dist/conf/aws-ec2_provision.sh
simulator/src/main/java/com/hazelcast/simulator/utils/CloudProviderUtils.java
simulator/src/main/java/com/hazelcast/simulator/wizard/Wizard.java
simulator/src/main/resources/awsEc2SimulatorProperties
simulator/src/main/resources/testSuite

This PR contains following enhancements for `simulator-wizard` command:
* Check whether a valid cloud provider is set through the `--cloudProvider` and throw a descriptive error if not, to prevent accidental typos like `aws` instead of `aws-ec2` and then chasing the root cause for a long time.
* Provide example `simulator.properties` with sensible defaults to illustrate the structure of the file to the new user and provide her a good starting point for editing. I'll probably add more example properties later (like selecting JDK version etc.).
* Make provisioner fail-fast when subnet ID is not specified. The change might look odd (like removing security groups config) but you'll find an explanation of the change directly on the line in this PR. …

Enhancements for simulator-wizard and provisioning in AWS

---

README.md
dist/src/main/dist/conf/simulator.properties
drivers/driver-hazelcast3/conf/install-hazelcast-support3.sh
drivers/driver-hazelcast4/conf/install-hazelcast-support4.sh

This PR contains small improvements to the ways of  specifying which version of Hazelcast you want to use for the test and where it comes from. In other words, these enhancements are related to `--version` flag. Namely:
* Undo hardcoded local Maven repository path. The user might have specified a custom one in her settings.xml, so Simulator should respect that. Newly, the script first reads the currently set path and then uses that.
* Provide ability to specify custom Maven settings.xml via `CUSTOM_MAVEN_SETTINGS` property in `simulator.properties`. This settings.xml will be used when using Maven for the retrieval of artifacts. This enables a use case that we had recently with a customer - customer couldn't access Maven Central due to security policies, but they had a company Nexus …

Improvements to version selection

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/DownloadTask.java

This PR fixes an issue of coordinator hanging indefinitely under some conditions. Consider following scenario (which is actually a reproducer).
Set `CUSTOM_MAVEN_SETTINGS` to non-existing file. During the driver installation phase of coordinator, the `install-hazecast4.sh` script fails here: https://github.com/hazelcast/hazelcast-simulator/blob/master/drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/hazelcast4/Hazelcast4Driver.java#L210 . This boils down to `System.exit()` being called (through here: https://github.com/hazelcast/hazelcast-simulator/blob/master/simulator/src/main/java/com/hazelcast/simulator/utils/BashCommand.java#L144) effectively shutting down the coordinator process.
Coordinator has a shutdown hook registered which contains a call of DownloadTask …

Fix deadlock when error occurs in DownloadTask during shutdown

---

dist/src/main/dist/conf/benchmark-report.py

When there is not data for a particular time series the script fails.
I have seen this happen with "Load Average 15 Minute" for short
benchmark runs.

Fix benchmark-report when there is no data

---

dist/src/main/dist/conf/benchmark-report.py
dist/src/main/dist/conf/init_report_files.sh

This PR fixes two minor issues and one big with `benchmark-report` script for generating the charts:
* **Warning messages when HDR files are not present** - trivial fix. For example, if you configure Simulator to stress the cluster with clients, the number of operations is tracked only on the clients. Therefore, the member workers won't generate any HDR files (= files measuring latency of the operations). However, `benchmark-report` expects it there anyway and if it's not in the worker directory, it prints error like `cp ... ...: File not found` which looks annoying. The solution is to simply copy them only if they exist. Relevant part of the PR: https://github.com/hazelcast/hazelcast-simulator/pull/1943/files#diff-aff6d044ebd89a44be2da1b433372e8c47982d885a43f9377a4cf5513297b258R23-R28
* …

Fix benchmark-report vertical drop in throughput charts + minor missing dstat fix

---

drivers/driver-hazelcast4/conf/install-hazelcast-support4.sh

In the training given by Jiri today we were not able to run a local test on MacOS.  The problem occurred when executing the "run" command, specifically while downloading Hazelcast 4.2 into the m2 repo. It does not affect Mac users who already have it downloaded.  The fix was in the "sed" commands that applies substitutions in  the "dependency-copy" pom.  I have made sure this works on MacOS BigSur but have not verified that this on Linux.

fix for install-hazelcast-support4.sh not working on MacOS

---

drivers/driver-hazelcast3/conf/install-hazelcast-support3.sh
drivers/driver-hazelcast4/conf/install-hazelcast-support4.sh

Fix a bug  introduced by https://github.com/hazelcast/hazelcast-simulator/commit/20c4ac2777130e879203917bbba12e7878b1197e which fixed it for OS X but broke it for Linux.
This fix works on both platforms.

Fix sed issues during Hazelcast downloading of Maven artifacts

---

dist/src/main/dist/conf/worker.sh_perf_flamegraph

Now it is at https://github.com/jvm-profiling-tools/perf-map-agent		
(was https://github.com/jrudolph/perf-map-agent before)

Use new repo url for perf-map-agent

---

drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/tests/map/MapEntryListenerTest.java

The `sleepSeconds` method is expecting number of seconds, not milliseconds. Therefore, we passed 8000 seconds for a sleep.
This is the root cause why after every release verification, the run waits for 2 hours 13 minutes 23 seconds  for completion of the MapEntryListenerTest as seen from the logs of e.g. 5.0-BETA-1 run:
```
INFO  19:55:42 MapEntryListener Waiting for all performance info
INFO  19:56:42 Performance MapEntryListener
Total running time 02d 02h 13m 23s
```
2 hours (7200 seconds) + 13 minutes (780 seconds) + 23 seconds = 8003 seconds. 
This PR fixes the waiting but is unrelated to OOME described here: https://github.com/hazelcast/hazelcast-simulator/issues/1879

Fix sleep time in MapEntryListenerTest

---

drivers/driver-hazelcast4plus/conf/install-hazelcast-enterprise4plus.sh

It's possible that I broke usage for 4.x but this is a quick fix for 5.0 as we're in the process of release verification. I'll take a look at it during the weekend.

Fix demand for -all artifact in Hazelcast 5

---

simulator/src/main/java/com/hazelcast/simulator/utils/ReportCsv.java

When the benchmark doesn't produce higher percenties the report.csv doesn't containt proper columns and HTML report cannot be generated:
```
Traceback (most recent call last):
File "/.../HazelcastSimulator/Dist/hazelcast-simulator-0.14-SNAPSHOT/conf/benchmark-report.py", line 1168, in <module>
htmlReport.generate()
File "/.../HazelcastSimulator/Dist/hazelcast-simulator-0.14-SNAPSHOT/conf/benchmark-report.py", line 1134, in generate
self.report = self.report + '<td>' + csvContents[j].split(',')[i].replace('"', '') + '</td>'
IndexError: list index out of range
```

Fix missing percentiles at csv

---

build
playbooks/install_simulator.yaml
src/agents_clear.py
src/agents_download.py
src/agents_start.py
src/agents_stop.py
src/agents_upload_driver.py
src/commit_sorter.py
src/inventory_cli.py
src/load_hosts.py
src/perf_analysis_cli.py
src/perfregtest_cli.py
src/perftest_cli.py
src/prepare_run.py
src/upload_hazelcast_jars.py
templates/storage-ec2/aws/auto_mount.py

This PR changes Python used in scripts from `#!/usr/bin/python3` to `#!/usr/bin/env python3`. This is good because in some environments we may not want to use python3 found in /usr/bin directory but rather get it from path. Also fixes one typo.

Use Python from environment

---

java/pom.xml

Sonar plugin was relocated https://mvnrepository.com/artifact/org.codehaus.mojo/sonar-maven-plugin/3.3.0.603. For whatever reason it issues a lot of warning when clicking sync button in IntelliJ. I can also reproduce the issue if I wrote `mvn -U dependency:resolve-plugins`. Using relocated reps solved the issue.

Relocate sonar plugin

---

src/perfregtest_cli.py

The ```-Dmaven.test.skip=true``` is honored by maven compiler plugin, the ```-DskipTests``` is not.

Skipping test compilation in perfregrtest

---

src/upload_hazelcast_jars.py

Current command `mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout` 
was returning empty on MacOS so jars in local repo could not be find.
With the fix here, command is working expectedly and jars are found.

Update maven command to get local repo path

---

java/simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java

A comma was missing between the last 2 values (total std and total
throughput).

Problem in SimulatorHistogramLogProcessor

---

playbooks/install_simulator.yaml

Somehow Ansible wants to choke on 'warn' nonsense; something that worked fine before. Great work Ansible team: you have earned another point. Earn some more and I'll be very happy to remove Ansible.

Fixed problem with ansible.

---

src/inventory_cli.py

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2018

Upgraded to Java 17 by default

---

README.md

Might be related to terraform or ansible version but `--list` did not exist for me, I think it is replaced with `--examples`:
```
$ inventory install java -h 
usage: inventory_cli.py [-h] [--url URL] [--examples] [--hosts HOSTS]
Install Java
options:
-h, --help     show this help message and exit
--url URL      The url of the JDK tar.gz file (default: https://download.java.net/java
/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz)
--examples     Shows example urls (default: False)
--hosts HOSTS  The target hosts. (default: all:!mc)
```

Update the command to list example Java URLS and fix a typo

---

src/perfregtest_cli.py

I am not sure if I changed `project_paths[-1]` correctly. `project_paths` variable did not exist in the scope though. So I guessed it is build_paths

Uncomment run method in perfregtest_cli

---

src/perf_analysis_cli.py

because the whole version is not used in directory names generated by perftest.

Use the first 10 characters of commits in summary cli 

---

README.md
src/simulator/perftest_report.py

I saw that it's a common theme to run the benchmarks and then do a comparison report using `perftest report`.  By default each `perftest run` creates a folder under `runs/BenchmarkName/` with current date and time as the folder name.
I found that each time I was checking what was the last folder name and copy-pasting... It's error-prone and irritating. I saw that Krzysztof used some script to automate getting simply last run of each benchmark.
This PR adds such possibility as a new flag of `perftest report`:
- `-l` or `--last` - take just the last (alphabetically) folder inside given directories to compare.

Add --last flag

---

README.md
templates/hazelcast5-ec2/tests.yaml

There was still a lot of legacy documentation related to Simulator 1.0 kicking around in the README - this commit addresses that and updates it all for Simulator 2.0.

Update README for Simulator 2.0 

---

bin/perfregtest
bin/perftest

So when rsync not found, these commands don't run.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2015

perftest/perfregtest rsync detection added.

---

java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepLoop.java

The logger was private but should be protected so that subclasses can access it. Resolves a few test failures.

Fix problem with TimeStepLoop logger.

---

templates/elasticache-cluster/aws/main.tf
templates/elasticache-cluster/inventory_plan.yaml
templates/hazelcast5-ec2/aws/main.tf
templates/hazelcast5-ec2/inventory_plan.yaml
templates/hazelcast5-hd-ec2/aws/main.tf
templates/hazelcast5-hd-ec2/inventory_plan.yaml
templates/sql-ec2-tstore/aws/main.tf
templates/sql-ec2-tstore/inventory_plan.yaml
templates/sql-ec2/aws/main.tf
templates/sql-ec2/inventory_plan.yaml
templates/sql-prunability-ec2/inventory_plan.yaml
templates/storage-ec2/aws/main.tf

The current configuration didn't work properly without fixes.
The whole thing is now simplified, you just need to uncomment the placement groups setting on load generator and the nodes and you are good to go.
Also tenancy/placementgroup for mc has been removed since it provides no value.
fixes https://github.com/hazelcast/hazelcast-simulator/issues/2052

Fixed problems with placement groups.

---

src/perftest_cli.py
src/simulator/perftest.py

This commit adds the `--skip_auto_gen_report` flag that allows the skipping of the `perftest report` execution after tests have been run if provided. This is particularly useful for situations such as release verification that are focused on pass/fail instead of performance analysis.
This commit also fixes an issue where some flags were only added to the coordinator arguments list if set to `True`, not when set to `False`.
This commit also changes the `test.properties` generation to use the `name` variable as the UID of test cases if provided, instead of always using the `class` name. This allows multiple test cases using the same test class in 1 test suite.
Also some typo fixes.

Perftest run auto_gen_report flag addition & some bug fixes

---

src/inventory_cli.py

The default JDK to use is JDK 21 since it is the latest LTS.
Also updated the example URLs.

Updated to JDK 21

---

playbooks/install_simulator.yaml

dstat is a mess because the project was abandoned. RHEL releases a new tool PCP that provides a drop in replacement for dstat and later dstat continues and now there are 2. Both provide dstat.

Install either dstat or pcp

---

templates/hazelcast5-ec2/hazelcast.xml
templates/hazelcast5-ec2/tests.yaml
templates/hazelcast5-hd-ec2/hazelcast.xml
templates/hazelcast5-hd-ec2/tests.yaml

Both hazelcast5-ec2 and hazelcast5-hd-ec2 have been:
- upgraded to 5.3.0
- make use of LongByteArrayMapTest
Enterprise now makes use of an offheap map by default.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2076

Cleaned up some ec2 templates

---

templates/hazelcast5-hd-ec2/inventory_plan.yaml
templates/hazelcast5-hd-ec2/tests.yaml

Number of created instances is larger than number of used instances. So resources are wasted.
fixes https://github.com/hazelcast/hazelcast-simulator/issues/2089

hazelcast5-hd-ec2 unused instances

---

java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java

Before it was 1 hour; now it is 24h.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2091

HdrProbe now tracks up to 24h of latency.

---

java/simulator/src/main/java/com/hazelcast/simulator/probes/Probe.java
java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/EmptyProbe.java
java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
java/simulator/src/main/java/com/hazelcast/simulator/test/TestContext.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContextImpl.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestManager.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepLoop.java
java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/EmptyProbeTest.java
java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java
java/simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TestContainer_BasicTest.java

Tests that rely on @Run, need to have access to Probe instances otherwise they can't record latency. So probe instances can now be obtained through the TestContext.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2099

Probes exposed through TestContext.

---

templates/hazelcast5-ec2/inventory_plan.yaml
templates/hazelcast5-hd-ec2/inventory_plan.yaml
templates/storage-ec2/inventory_plan.yaml

The default AMI is listed, but the user isn't. This PR fixes that.
Fixes:
https://github.com/hazelcast/hazelcast-simulator/issues/2107

Templates are missing ec2 user

---

java/simulator/src/main/java/com/hazelcast/simulator/probes/LatencyProbe.java
java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrLatencyProbe.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContextImpl.java
java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrLatencyProbeTest.java

Apparently, it can happen that the elapsed time is negative:
```
cause=java.lang.ArrayIndexOutOfBoundsException: Histogram recorded value cannot be negative.
at org.HdrHistogram.AbstractHistogram.countsArrayIndex(AbstractHistogram.java:2404)
at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:559)
at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:467)
at org.HdrHistogram.Recorder.recordValue(Recorder.java:136)
at com.hazelcast.simulator.probes.impl.HdrProbe.recordValue(HdrProbe.java:70)
at CreateDestroyICacheTestLoopCacheCreateDestroy.timeStepLoop(CreateDestroyICacheTestLoopCacheCreateDestroy.java:43)
at com.hazelcast.simulator.worker.testcontainer.TimeStepLoop.run(TimeStepLoop.java:110)
at java.lang.Thread.run(Thread.java:748)
at …
```

Handle negative elapsed time on HdrLatencyProbe.

---

src/simulator/ssh.py
src/upload_hazelcast_jars.py

The current method for uploading driver artifacts is deleting them from the target member and using `scp` for copying the entire files there. This is done even if the target file is identical to the version to be uploaded, making each test run to upload all drivers to all test machines, making testing slow on machines through slow networks. This commit changes the uploading method to using `rsync` over ssh to copy only if the driver files to upload are absent in the target or different to the version in local.

Upload drivers with rsync instead of scp

---

playbooks/install_simulator.yaml

When 'inventory install simulator' is called, it should ensure that rsync is installed on the remote machines since rsync is used to upload the hazelcast jars.

inventory install simulator should include rsync

---

src/simulator/perftest_report_html.py

If a directory containing images doesn't exist (e.g. dstat while dstat disabled), the report generation should skip it instead of throwing an error.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2130

Report generation: protection against non existing dirs.

---

performance_notes.txt

Included section in performance_notes.txt how to use async_profiler without JFR but making a flamegraph directly.

Improved async_profiler doc

---

java/simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollector.java
java/simulator/src/test/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollectorTest.java

3 columns are being printed: avg, p999 and the max.
```
FO  05:02:36 map Running 00d 00h 02m 39s ( 88.33%)    96,585,791 ops   610,472.29 ops/s         12 ms (avg)        595 ms (99.9th)        711 ms (max)
INFO  05:02:37 map Running 00d 00h 02m 40s ( 88.89%)    97,198,883 ops   613,037.38 ops/s      9,517 µs (avg)    529,006 µs (99.9th)    543,686 µs (max)
INFO  05:02:38 map Running 00d 00h 02m 41s ( 89.45%)    97,810,848 ops   611,899.57 ops/s         10 ms (avg)        739 ms (99.9th)        764 ms (max)
INFO  05:02:39 map Running 00d 00h 02m 42s ( 90.00%)    98,421,879 ops   610,993.83 ops/s      9,446 µs (avg)    537,919 µs (99.9th)    594,542 µs (max)
INFO  05:02:40 map Running 00d 00h 02m 43s ( 90.56%)    99,032,041 ops   610,127.92 ops/s      9,347 µs (avg)    886,571 µs (99.9th) …
```

Minor performance output enhancement.

---

src/simulator/inventory_terraform.py

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2145

Fixes 'inventory destroy' when .terraform is missing.

---

README.md

Taken from our distribution module's `jvm.options` for Java 9+

Java 9+ GC parameters update

---

templates/cp-ec2/setup
templates/cp-ec2/teardown
templates/elasticache-cluster/setup
templates/elasticache-cluster/teardown
templates/hazelcast5-ec2/setup
templates/hazelcast5-ec2/teardown
templates/hazelcast5-hd-ec2/setup
templates/hazelcast5-hd-ec2/teardown
templates/sql-ec2-tstore/setup
templates/sql-ec2-tstore/teardown
templates/sql-ec2/setup
templates/sql-ec2/teardown
templates/sql-prunability-ec2/setup
templates/sql-prunability-ec2/teardown
templates/storage-ec2/setup
templates/storage-ec2/teardown

Each template has a setup/teardown script to make setting up the environment easier and less error prone.
Also the Java version is explicit instead of relying on whatever default is provided by some snapshot version of the Simulator.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2115

Added setup/teardown scripts

---

src/simulator/perftest_report.py

The problem was that if the preserve time flag was set, the periods were not loaded and this leads to problems further down the line.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2157

Resolved 'perftest report -t' problem.

---

src/simulator/perftest_report_common.py
src/simulator/perftest_report_hdr.py

So instead of always using us, the time unit is picked based on the value.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2151

Uses appropriate time unit in latency distribution per %

---

bin/perftest

Since gnuplot isn't used any longer, the check can be removed.

Removed gnuplot check

---

playbooks/install_async_profiler.yaml
playbooks/install_iperf3.yaml
playbooks/install_java.yaml
playbooks/install_simulator.yaml

The variables should be declared as a dictionary and not as a list.
Fixes partially https://github.com/hazelcast/hazelcast-simulator/issues/2044
It doesn't resolve all deprecation warnings. There are some that are caused by some obscure python problem.

Resolve 'var list' ansible deprecation warnings.

---

java/simulator/src/main/java/com/hazelcast/simulator/utils/CommonUtils.java

`JarFile` is already `Closeable`, so can use existing method

Remove unnecessary `closeQuietly` `JarFile` variant

---

playbooks/install_async_profiler.yaml
src/inventory_cli.py

This provides more flexibility because you can control the exact binary to download including control over the ISA.

async_profiler install using url.

---

java/archetype/pom.xml
java/drivers/driver-couchbase/pom.xml
java/drivers/driver-hazelcast3/pom.xml
java/drivers/driver-hazelcast4plus/pom.xml
java/drivers/driver-ignite2/pom.xml
java/drivers/driver-infinispan11/pom.xml
java/drivers/driver-jedis3/pom.xml
java/drivers/driver-lettuce6/pom.xml
java/drivers/driver-lettucecluster6/pom.xml
java/drivers/driver-memcached/pom.xml
java/drivers/driver-mongodb/pom.xml
java/drivers/pom.xml
java/integration-tests/pom.xml
java/pom.xml
java/simulator/pom.xml

The minimum version required (3.0.1) was [released in 2010](https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.0.1/), so it's unlikely anyone would be using an older version, and this [requirement was added in 2015](https://github.com/hazelcast/hazelcast-simulator/commit/7310feeffd1103450e8fdb87c9ddbb9bc77f7ccc).
Fixes: https://github.com/hazelcast/hazelcast-simulator/issues/2172

Remove Maven `prerequisites` - address warnings

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/BuildInfoUtils.java
java/pom.xml
java/simulator/pom.xml
java/simulator/src/main/java/com/hazelcast/simulator/worker/ScriptExecutor.java

In 47d54e8a13b4242cee8bc60a84f84141f9be2034, the `hazelcast.version` was upgraded to `5.4`, which requires Java 17
Changes:
- code level `hazelcast-simulator` upgraded to Java 17
- added `nashorn` dependency to support Javascript evaluation as [no longer bundled with JDK](https://github.com/szegedi/nashorn/wiki/Using-Nashorn-with-different-Java-versions)
- upgrading the build jobs to JDK 17 (outside of this PR)
[Slack discussion](https://hazelcast.slack.com/archives/C034XSXE6/p1705424515952179).

Upgrade to Java 17

---

README.md
src/simulator/perftest.py
src/simulator/perftest_report.py
src/simulator/perftest_report_common.py

This PR makes it easier to run and compare a set of tests across multiple named test configurations/versions and avoids necessity to manually rename directories for each run. Long labels make it easy to do matrix comparisons (test name + label).
Example how this can be used: https://hazelcast.atlassian.net/wiki/spaces/EN/pages/4766597215/Jet+Light+Jobs+Performance#Appendix (commands) and the same document contains generated tables (slightly modified) and graphs.

Add easy way to generate test comparison reports with readable labels

---

java/drivers/driver-hazelcast4plus/conf/configure.py

The members property already gets replaced by node_count in the _sanitize_test method. So we should use node_count.

Use node_count instead of members.

---

README.md

Not required by perftest directly but it is required to interact with the aws api.  The "setup" script in the performance test fails without it.

add boto3 to list of required packages

---

performance_notes.md
playbooks/install_async_profiler.yaml

Async profiler install broke after upgrading to latest async profiler.

Fixed async profiler installation problems

---

java/drivers/driver-hazelcast4plus/conf/install.py

Currently simulator will throw an error if one tries to use a version >5. This change permits the use of the new 6.0 HZ version.

Support Hazelcast versions 5+ [HZG-197] 

---

README.md
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hazelcast4plus/Hazelcast4PlusDriver.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/HazelcastUtils.java

Introduces ability to assign cp-priority to members.
Simply use the the internal ip of an agent and assign the priority in the test.yaml file.
Example usage : 
```yaml
cp_priorities:
- address: 10.0.55.178
priority: 1
- address: 10.0.55.179
priority: 2

Support CP Priority assignment [HZG-205]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/DatasetReader.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/VectorCollectionSearchDatasetTest.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/readers/HDF5DatasetReader.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/readers/NpyArchiveDatasetReader.java

- run queries in a cycle, instead of just once
- allow loading a separate test dataset using `testDatasetUrl`

Push improvements from project-x

---

java/drivers/driver-hazelcast4plus/pom.xml
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/VectorCollectionSearchDatasetTest.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/BuildInfoUtils.java
java/pom.xml
java/settings.xml

Upgrade benchmark code to 6.0.0-SNAPSHOT. Jenkins CI job was changed to use private snapshot repository configuration.
Improved vector collection tests:
- configurable backup count
- reuse existing collection
- smaller memory usage

Vector tests improvements

---

templates/hazelcast5-ec2/inventory_plan.yaml

This may have worked correctly with report generation at some point, however it no longer works with report generation (and maybe other things). Therefore, for now, we only support the default generated inventory parameters which is what most (if not all) people are using.

Remove ec2-user  Example from EC2 Inventory Template

---

src/simulator/perftest_report_hdr.py

Report benchmarks in summary tab in predictable - alphabetic order, the same in which they are executed.

Report benchmarks in summary tab in predictable order

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/VectorCollectionPutDatasetTest.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/HazelcastUtils.java

More reliable VectorCollection `optimize` time reporting after https://github.com/hazelcast/hazelcast-mono/pull/3639

Wait for parked backup execution in vector optimization tests [AI-192]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/vector/DatasetReader.java

Loading test dataset in `DatasetReader` takes some time and happens for each step in multi-step tests. Caching should make the test preparation faster and reduce memory footprint on the load generator.

Cache DatasetReader in vector collection tests

---

java/drivers/driver-hazelcast4plus/pom.xml
playbooks/install_tls_keystores.yaml
src/inventory_cli.py
templates/hazelcast5-tls-ec2/.gitignore
templates/hazelcast5-tls-ec2/README.md
templates/hazelcast5-tls-ec2/ansible.cfg
templates/hazelcast5-tls-ec2/aws/main.tf
templates/hazelcast5-tls-ec2/client-hazelcast.xml
templates/hazelcast5-tls-ec2/hazelcast.xml
templates/hazelcast5-tls-ec2/inventory_plan.yaml
templates/hazelcast5-tls-ec2/setup
templates/hazelcast5-tls-ec2/teardown
templates/hazelcast5-tls-ec2/tests.yaml

Add ansible playbook for reproducible TLS keystore + truststore generation and distribution which can be called via `inventory`. Added a template which sets everything up for the user. Both jdk and openssl TLS supported. Netty dependency versions have been bumped to their latest hazelcast platform versions to support this.

Add simulator template with TLS enabled [DEX-338]

---

templates/hazelcast5-cp-ec2/aws/main.tf
templates/hazelcast5-cp-ec2/inventory_plan.yaml
templates/hazelcast5-ec2/aws/main.tf
templates/hazelcast5-ec2/inventory_plan.yaml
templates/hazelcast5-hd-ec2/aws/main.tf
templates/hazelcast5-hd-ec2/inventory_plan.yaml
templates/hazelcast5-sql-ec2-tstore/aws/main.tf
templates/hazelcast5-sql-ec2/aws/main.tf
templates/hazelcast5-sql-prunability-ec2/aws/main.tf
templates/hazelcast5-storage-ec2/aws/main.tf
templates/hazelcast5-tls-ec2/aws/main.tf
templates/hazelcast5-tls-ec2/inventory_plan.yaml

Added `extraTags` block to `inventory_plan.yaml` which allows adding additional tags to all aws resources created for a simulation.

Support adding extra tags to AWS resources [DEX-341]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java

**NOTES:**
- Extend `LongByteArrayMapTest` to support multiple maps
- `LongByteArrayMapTest` has been chosen for a specific customer [benchmark](https://hazelcast.atlassian.net/wiki/spaces/TES/pages/5847285775/Visa+Workload+Validation+-+Approach+Roles+Responsibilities+Client+Count+Thresholds)

Adjust LongByteArrayMapTest to support multiple maps [DEX-340]

---

playbooks/install_java.yaml
templates/hazelcast5-cp-ec2/aws/main.tf
templates/hazelcast5-ec2/aws/main.tf
templates/hazelcast5-hd-ec2/aws/main.tf
templates/hazelcast5-sql-ec2-tstore/aws/main.tf
templates/hazelcast5-sql-ec2/aws/main.tf
templates/hazelcast5-sql-prunability-ec2/aws/main.tf
templates/hazelcast5-storage-ec2/aws/main.tf
templates/hazelcast5-tls-ec2/aws/main.tf

Configures the simulator hosts to allow the java processes to create raw sockets, adds ingress rule allowing instances to connect with the icmp protocol.

Add native ping failure detector support for simulator runs [DEX-360]

---

java/simulator/src/main/java/com/hazelcast/simulator/utils/BatchedHistogramLogProcessor.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/HistogramLogProcessor.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java
src/simulator/perftest_report_hdr.py

For a large number of workers it currently takes a long time to process all hdr files, e.g. for 1025 workers it took over 1 hour. This change improves the speed by 10x, the same run took 6mins to process them all. The improvements come from running all processing in parallel in a single jvm instance instead of sequentially processing each file in separate jvm processes.

Improve hdr file processing performance [DEX-353]

---

java/simulator/src/main/java/com/hazelcast/simulator/utils/BatchedHistogramLogProcessor.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/HistogramLogProcessor.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java

```
INFO  12:06:49 Processing 6002 hdr files
WARN  12:06:49 Log file parsing error at line number 85: line appears to be malformed.
Traceback (most recent call last):
File "/Users/alaktionov/IdeaProjects/hazelcast-simulator/bin/../src/perftest_cli.py", line 63, in <module>
PerftestCli()
File "/Users/alaktionov/IdeaProjects/hazelcast-simulator/bin/../src/perftest_cli.py", line 37, in __init__
getattr(self, args.command)()
File "/Users/alaktionov/IdeaProjects/hazelcast-simulator/bin/../src/perftest_cli.py", line 58, in report
PerfTestReportCli(sys.argv[2:])
File "/Users/alaktionov/IdeaProjects/hazelcast-simulator/src/simulator/perftest_report.py", line 262, in __init__
prepare(config)
File "/Users/alaktionov/IdeaProjects/hazelcast-simulator/src/simulator/perftest_report.py", line 28, in …
```

Update BatchedHistogramLogProcessor to improve hdr files processing [DEX-353][DEX-377]

---

src/simulator/perftest_report.py
src/simulator/perftest_report_common.py
src/simulator/perftest_report_dstat.py
src/simulator/perftest_report_hdr.py
src/simulator/perftest_report_operations.py

When aggregating all run data the dataframe concatenation is currently very slow for a run with many workers. The current implementation is repeatedly copying the same data. This change increases the memory used by less than the size of the final dataframe but the time taken to run the operation is greatly improved. For example on my machine the analyze step takes roughly 2 hours with 6k workers before this change, with this change it takes less than a minute.

Improve dataframe concatenation speed by using more memory [DEX-385]

---

java/simulator/src/main/java/com/hazelcast/simulator/utils/ReportHistogramLogProcessor.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java
src/simulator/perftest_report_hdr.py

Remove duplication of work when processing each hdr file by supporting more control over the output file formats. Now we allow the overall latency distribution to be output in .hgrm but the latency over time to be output in .csv instead of requiring both files to have the same format.

Remove duplicated work processing hdr files in report [DEX-376]

---

java/simulator/src/main/java/com/hazelcast/simulator/utils/HistogramLogMerger.java
src/simulator/perftest_report_hdr.py

Fix to __merge_worker_hdr step: Write all files list into a file and read from that file while processing in Java.
I also added some extra logs during hdr merge step to understand the progress since this step lasts too long. I write the log after each merged hdr like this: 
```
INFO  23:20:01 [2025-04-18 23:20:01] [HistogramLogMerger] Added merged histogram 1082 to run_dir/map.get.hdr
```
With this fix, the report generation can be run on lab servers. I ran it on lab server 1. I was able to generate the 12k report on lab server 101 in 1.5 hours.
```
47413.55user 4561.21system 1:30:34elapsed 956%CPU
```
Out of this 1/5 hours, 
- 30 mins is hdr_merge step. 
- 20 mins: Processing hdr files: Done 1219.31 seconds
- 6 mins: Loading csv files.
- 26 mins: Writing combined run data to: …

Fix merge hdr step during report processing [DEX-375]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java

We like to be able to hit to the same keys on a certain probability to generate some hit ratio for common used keys. This is especially useful if you like to create some hit ratio for near cache tests.
This change gives the capability to create a hit ratio of `fixedKeysPercentage`, assuming that the near cache local keys stored these keys and they are not evicted.
Added 2 new optional test parameters, the `fixedKeysPercentage` and `fixedKeysProbability` to the test. Definition of these fields are:
```
/**
* The percentage of total keys to be used as fixed key domain. If set to 0, all
* keys are random. you need to also set the fixedKeysProbability to a value
* greater than 0 to make the fixed key domain to be used.
*/
public int fixedKeysPercentage = 0;
/**
* The probability of using a …
```

Add capability to define  usage of non-random keys (e.g. to generate near cache hits) [DEX-408]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java

Changed the test so that the fixed key set is only used for get operation to get better deterministic near cache hit ratios.
If you use it also for put operations, it will cause invalidation of the fixed key which we want to hit and hence decrease desired hit ratio.

Changed the test so that the fixed key set is only used for get operation [DEX-418]

---

README.md
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hazelcast4plus/Hazelcast4PlusMultiDriver.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hazelcast4plus/HazelcastInstances.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hz/HazelcastTest.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/helpers/HazelcastTestUtils.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java
java/drivers/driver-hazelcast4plus/src/test/java/com/hazelcast/simulator/tests/map/helpers/AssignKeyToIndexTest.java
java/simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerParameters.java
java/simulator/src/main/java/com/hazelcast/simulator/drivers/Convertible.java
java/simulator/src/main/java/com/hazelcast/simulator/drivers/Driver.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java

Currently the simulator only supports one hazelcast client per loadgenerator worker process. This means if you want to run experiments to see the behaviour of a cluster with many client connections you need to create many processes and this means larger test setup times, more expensive tests and slower report generation. 
This PR adds a new driver and configuration parameter to the tests.yaml "clients_per_loadgenerator" which allow you to create multiple clients for each loadgenerator while retaining backwards compatibility with existing tests.
It also adds the ability to change the driver class used with configuration making it easier to add new driver implementations in future.

Add driver support for multiple clients per worker

---

java/drivers/driver-hazelcast4plus/conf/install.py
java/drivers/driver-hazelcast4plus/pom.xml
java/pom.xml
java/settings.xml

Ensures that users without hazelcast credentials can use the simulator tooling. This is a temporary solution. The user must have an enterprise license and use   `driver: hazelcast-enterprise5`

Only use public enterprise repo

---

java/drivers/driver-hazelcast4plus/pom.xml

Renames the version on `master` from `6.0-SNAPSHOT` to `5.6-SNAPSHOT`.
Supports https://github.com/hazelcast/hazelcast-mono/pull/4852
Fixes: [CTT-504](https://hazelcast.atlassian.net/browse/CTT-504)
[CTT-504]: https://hazelcast.atlassian.net/browse/CTT-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Relabel `master` from `6.0-SNAPSHOT` to `5.6-SNAPSHOT` [CTT-504]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/BuildInfoUtils.java

The test was not updated in https://github.com/hazelcast/hazelcast-simulator/pull/2285

Fix BuildInfoUtilsTest after change to 5.6 [CTT-504]

---

.github/workflows/ci.yml
.github/workflows/security-scan.yml

Fixed invalid GitHub Actions syntax in the CI workflow where non-existent `failure()` and `cancelled()` functions were being used instead of the correct `${{ job.status }}` context variable. This change ensures the build summary step can properly determine and display the overall workflow status.

fix: Replace invalid failure() and cancelled() functions with job.status
