stabilizer/src/main/java/com/hazelcast/stabilizer/common/StabilizerProperties.java

Version spec is now picket from a local stabilizer.properties as well

---

stabilizer/src/main/java/com/hazelcast/stabilizer/test/utils/TestUtils.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapStoreTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapTimeToLiveTest.java

moving asserts into assertTrueEventually,  on 2 test that used to use looped sleeping

using assertTrueEventually,

---

dist/src/main/dist/conf/client-hazelcast.xml
dist/src/main/dist/conf/hazelcast.xml
dist/src/main/dist/tests/synthetic/synthetic.properties
tests/src/main/java/com/hazelcast/stabilizer/tests/synthetic/SyntheticBackupOperation.java
tests/src/main/java/com/hazelcast/stabilizer/tests/synthetic/SyntheticOperation.java
tests/src/main/java/com/hazelcast/stabilizer/tests/synthetic/SyntheticRequest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/synthetic/SyntheticRequestPortableFactory.java
tests/src/main/java/com/hazelcast/stabilizer/tests/synthetic/SyntheticSerializableFactory.java
tests/src/main/java/com/hazelcast/stabilizer/tests/synthetic/SyntheticTest.java

Renamed SyntheticBackPressureTest to SyntheticTest since we use it for a lot of purposes apart from backpressure

SyntheticTest improvements

---

tests/src/main/java/com/hazelcast/stabilizer/tests/map/GrowingMapTest.java

Mostly split up `run()` method in little chunks which should be easier to read. Even IntelliJ was complaining that it couldn't analyze the `run()` method because if it's complexity.
Local test run finished without errors.

Cleanup of GrowingMapTest.

---

stabilizer/src/main/java/com/hazelcast/stabilizer/provisioner/Provisioner.java

new output
provisioner --terminate
INFO  11:59:02 Hazelcast Stabilizer Provisioner
INFO  11:59:02 Version: 0.4-SNAPSHOT, Commit: 12b30e9, Build Time: 26.02.2015 @ 11:51:12 UTC
INFO  11:59:02 STABILIZER_HOME: /home/danny/hazelcast-stabilizer-0.4-SNAPSHOT
INFO  11:59:02 Loading stabilizer.properties: /disk1/danny/awsPerf/stabilizer.properties
INFO  11:59:02 ==============================================================
INFO  11:59:02 Terminating 5 aws-ec2 machines (can take some time)
INFO  11:59:02 ==============================================================
INFO  11:59:02 Current number of machines: 5
INFO  11:59:02 Desired number of machines: 0
INFO  11:59:18     54.159.178.134 Terminating
INFO  11:59:51 Updating /disk1/danny/awsPerf/agents.txt
INFO  11:59:51 Duration: 00d 00h 00m 48s …

fix termination

---

README.md
docs/MANUALSETUP.md

documentation for manual machine setup

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/tasks/AbstractWorkerTask.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapPredicateTest.java

Added new method to `AbstractWorkerTask` to retrieve the random generator instance, so we don't have to implement all it's methods.

Cleanup of MapPredicateTest.

---

stabilizer/src/main/java/com/hazelcast/stabilizer/worker/selector/OperationSelectorBuilder.java
stabilizer/src/test/java/com/hazelcast/stabilizer/worker/selector/OperationSelectorTest.java

Fixed floating point error in `OperationSelectorBuilder`. Added test with (before failing) probabilities.

Fixed floating point error in OperationSelectorBuilder

---

dist/src/main/dist/tests/map/mapreduce.properties
tests/src/main/java/com/hazelcast/stabilizer/tests/map/MapReduceTest.java
tests/src/main/java/com/hazelcast/stabilizer/tests/map/helpers/MapReduceOperationCounter.java

Test doesn't complete, neither in `master` branch nor the refactored version. The inner `EmployeeCollator` class is not used (only remaining warning), maybe this part is still missing in the test.

Cleanup of MapReduceTest

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/remoting/AgentClient.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/remoting/AgentsClient.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java

* Fixed AgentSmokeTest
* Cleanup of Agent related classes

Fixed AgentSmokeTest

---

simulator/src/main/java/com/hazelcast/simulator/communicator/CommunicatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/AwsProvisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/AwsProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Bash.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/CloudInfo.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/CloudInfoCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ComputeServiceBuilder.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/HazelcastJars.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/TemplateBuilder.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/git/BuildSupport.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/git/GitRepository.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/git/GitSupport.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/git/HazelcastFilenameFilter.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/git/HazelcastJARFinder.java
simulator/src/main/java/com/hazelcast/simulator/utils/CommonUtils.java
simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java

With this PR also some FindBugs issues are gone (possible NPE and unused return values etc.).

Cleanup of provisioner package and related classes.

---

archetype/src/main/resources/archetype-resources/src/main/java/ExampleTest.java
archetype/src/main/resources/archetype-resources/workdir/test.properties
docs/TESTS.md
tests/src/main/java/com/hazelcast/simulator/tests/ExampleTest.java

If it is merged , i will change documentation in hazelcast repo.

renewed ExampleTests according to new approach

---

simulator/src/main/java/com/hazelcast/simulator/provisioner/git/BuildSupport.java
simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/main/java/com/hazelcast/simulator/worker/TestContainer.java
tests/src/main/java/com/hazelcast/simulator/tests/map/helpers/ZipfianGenerator.java

FindBugs was complaining about
* `Boolean` vs. `boolean` in `String.format()`
* a modifiable `Set` being `public`
* unused field
The first fix is from my internal compiler (space before newline).

Fixed some FindBugs issues

---

visualiser/src/main/java/com/hazelcast/simulator/visualiser/Main.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/data/AggregatedDataSet.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/data/BenchmarkResults.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/data/Model.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/data/SimpleHistogramDataSetContainer.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/io/ResultParserWorker.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/Chart.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/LoadedBenchmarks.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/MainUI.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/ProbesCheckboxes.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/utils/DataSetUtils.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/utils/FileUtils.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/utils/ListenerUtils.java

* Window is now auto-maximized.
* JFileChooser is now read-only (no more renames on click).
* JFileChooser is now automatically opened on program start.
* JSlider have clickable tracks now.
* JSlider don't scroll to negative bounds anymore.
* JSlider have reasonable minimum values.
* JSlider horizontal max values are now calculated from histograms (max latency).
* ProbesCheckboxes are auto-selected after loading a file.
* updateChart() is called automatically after loading a file.

Enhanced visualizer tool

---

simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java

Should be a proper fix now which does a shutdown of all obvious and hidden thread pools in the Provisioner.

Fixed Provisioner shutdown

---

checkstyle/suppressions.xml
simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupportTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_bindProperty_NonNumericalTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_bindProperty_NumericalTest.java

* Increased code coverage of `PropertyBindingSupport` to 100%
* Refactored class to reduce NPath and cyclic complexity
* Split up test files to reduce number of methods warning
* Suppressed filename check for test classes

Increased PropertyBindingSupport to 100% code coverage

---

visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/AccuracyRadioButtons.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/Chart.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/ui/MainUI.java
visualiser/src/main/java/com/hazelcast/simulator/visualiser/utils/DataSetUtils.java

* Added accuracy buttons to merge histogram values of high latency probes into the same histogram bin to get a proper visualization
* Stopped to add empty histogram bins to plot which makes the plot.getXXXAxis().setAutoRange(true) working
* Multiplied the values of a histogram bin with the width of the bin to display the correct value

Fixed a display bug in Visualizer

---

tests/src/main/java/com/hazelcast/simulator/tests/map/StringStringMapTest.java

Fixing #353
Results for 100,000 keys:
Before: 25s
After: 1s

Leverage asynchronous IMap API with a manual back-pressure to speed-up an initial data load.

---

tests/src/main/java/com/hazelcast/simulator/tests/map/StringStringMapTest.java

Use set probability to invoke IMap::set instead of relying on a boolean flag

---

dist/src/main/dist/user-lib/readme.txt
simulator/src/main/java/com/hazelcast/simulator/agent/workerjvm/WorkerJvmLauncher.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

add /user-lib/* to the class path  
this is need to enable us to work with other external test repos

worker class path

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/MapStreamer.java
tests/src/main/java/com/hazelcast/simulator/tests/map/SqlPredicateTest.java
utils/src/main/java/com/hazelcast/simulator/utils/CommonUtils.java

It allows fast initial data load into a map.
It's intended to be used during a test warm-up phase.

MapStreamer Abstraction Implemented

---

tests/src/main/java/com/hazelcast/simulator/tests/map/MapTransactionTest.java

2. Added a property to select TransactionType

1. MapTransactionTest refactored to use AbstractionWorker

---

simulator/src/main/java/com/hazelcast/simulator/agent/remoting/AgentRemoteService.java
utils/src/main/java/com/hazelcast/simulator/utils/CommonUtils.java
utils/src/main/java/com/hazelcast/simulator/utils/HostAddressPicker.java

Fixes #604
Simulator now works even when only a local loopback is available.
Agent now listen on all interfaces.

Simulator now works even when only a local loopback is available.

---

tests/src/main/java/com/hazelcast/simulator/tests/map/SqlPredicateTest.java

+ max age is now a test property

SqlPredicateTest uses AbstractWorker

---

dist/src/main/dist/conf/client-hazelcast.xml
dist/src/main/dist/conf/hazelcast.xml

I need a place holder of a licence key,  if we are using the enterprise mode,  we can inject a key hear

place holder for licence key

---

tests/src/main/java/com/hazelcast/simulator/tests/map/MapEntryListenerTest.java

Test was chosen because of:
```
MapEntryListenerTest.java:179:9: Cyclomatic Complexity is 16 (max allowed is 12).
MapEntryListenerTest.java:179:9: Method length is 76 lines (max allowed is 60).
MapEntryListenerTest.java:179:9: NPath Complexity is 686 (max allowed is 50).
```

Cleanup of MapEntryListenerTest.

---

simulator/src/main/java/com/hazelcast/simulator/worker/WorkerPerformanceMonitor.java

Fixes #643 IllegalMonitorState WorkerPerformanceMonitor

---

simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java

Class was chosen because of:
```
PropertyBindingSupport.java:95:5: Cyclomatic Complexity is 13 (max allowed is 12).
PropertyBindingSupport.java:95:5: NPath Complexity is 81 (max allowed is 50).
```
All tests are still green and CheckStyle is happy now.

Reduced NPath and cyclomatic complexity of PropertyBindingSupport.java

---

archetype/src/main/resources/archetype-resources/pom.xml

Fixes problem with the java version in the archetype

---

dist/src/main/dist/tests/map/maptransactionalgetforupdate.properties
tests/src/main/java/com/hazelcast/simulator/tests/map/MapTransactionGetForUpdateTest.java

Config options for the map tx test

---

dist/src/main/dist/conf/simulator.properties
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

Fixes #665 provisioner ignores --scale with local cloud provider
Fixes #664 provisioner assumes ec2 cluster when trying to terminate

Added static cloud provider

---

dist/src/main/dist/tests/genericoperation.properties
tests/src/main/java/com/hazelcast/simulator/tests/GenericOperationTest.java

test that puts pressure on generic operations.

GenericOperationTest

---

simulator/src/main/java/com/hazelcast/simulator/worker/tasks/AbstractWorker.java

Added a `stopWorker()` and `stopTestContext()` method to AbstractWorkerTask.

Added a stopWorker() method to AbstractWorkerTask.

---

simulator/src/main/java/com/hazelcast/simulator/worker/metronome/SimpleMetronome.java
simulator/src/test/java/com/hazelcast/simulator/worker/metronome/SimpleMetronomeTest.java

Should ease the creation of tests with requirements like "limit to 5000 op/s".

Add frequency creation to SimpleMetronome.

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunTestSuiteTest.java

* Changed `TestCaseRunner` to wait indefinitely for test if duration is zero or negative.
* Increased code coverage of `TestCaseRunner` to 100% line coverage.

Wait for test if duration is zero or negative

---

utils/src/main/java/com/hazelcast/simulator/utils/FileUtils.java

Fixed NPE in FileUtils if wildcard in classpath didn't match anything.

Fixed NPE in FileUtils

---

probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbe.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionResult.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/LatencyDistributionResult.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/MaxLatencyResult.java
probes/src/main/java/com/hazelcast/simulator/probes/probes/impl/OperationsPerSecResult.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/ConcurrentProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/HdrLatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/LatencyDistributionProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/MaxLatencyProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/OperationsPerSecProbeTest.java
probes/src/test/java/com/hazelcast/simulator/probes/probes/impl/ProbeTestUtils.java

Should fix https://github.com/hazelcast/hazelcast-simulator/issues/550

Increased code coverage of probes implementation package.

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/test/TestSuite.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunTestSuiteTest.java

* Added new cli option --waitForTestCaseCompletion to properly wait for TestCase to finish its runtime. Can be combined with --duration.
* Fixed bug with Infinity performance report due to --duration 0s.
* Increased code coverage of CoordinatorCli.

Implemented proper solution for --duration 0s

---

tests/src/main/java/com/hazelcast/simulator/tests/map/PagingPredicateTest.java

We already have `MapPredicateTest` which can exercise `PagingPredicate`, but I believe having a dedicated test is a good thing as it allows fine-tuning without introducing additional noise into the general-purpose  `MapPredicateTest`.

PagingPredicateTest

---

checkstyle/suppressions.xml
dist/src/main/dist/bin/visualizer
dist/src/main/dist/conf/visualizer-log4j.xml
pom.xml
visualizer/pom.xml
visualizer/src/main/java/com/hazelcast/simulator/visualizer/Main.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/data/AggregatedDataSet.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/data/BenchmarkResults.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/data/Model.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/data/SimpleHistogramDataSetContainer.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/io/ResultParserWorker.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/ui/AccuracyRadioButtons.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/ui/AutoScaleRadioButtons.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/ui/Chart.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/ui/LoadedBenchmarks.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/ui/MainUI.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/ui/ProbesCheckboxes.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/utils/DataSetUtils.java
visualizer/src/main/java/com/hazelcast/simulator/visualizer/utils/ListenerUtils.java

This should match our company naming policy.

Renamed Visualiser to Visualizer

---

dist/src/main/dist/simulator-tests/test.properties
tests/src/main/java/com/hazelcast/simulator/tests/map/MapStoreTest.java

Cleanup of `MapStoreTest` due to CheckStyle errors.
This is the last class which generates CheckStyle errors!

Cleanup of MapStoreTest

---

simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupportTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_bindProperty_NonNumericalTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/PropertyBindingSupport_bindProperty_NumericalTest.java

Fixes #705 binding to a non public field should not be allowed.

Fixes 705: binding to non public property not allowed

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/remoting/AgentsClient.java

This should fix #699.
Does someone see any negative side effect with this solution?

Fixed InterruptedException during shutdown

---

tests/src/main/java/com/hazelcast/simulator/tests/executor/ExecutorTest.java

It compiles against Hazelcast 3.6-SNAPSHOT again.

Deprecated call replaced

---

dist/src/main/dist/conf/client-hazelcast.xml
dist/src/main/dist/conf/hazelcast.xml
tests/src/main/java/com/hazelcast/simulator/tests/map/SerializationStrategyTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/DataSerializableDomainObject.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/DomainObject.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/DomainObjectFactory.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/IdentifiedDataSerializableDomainObject.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/IdentifiedDataSerializableObjectFactory.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/PortableDomainObject.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/PortableObjectFactory.java
tests/src/main/java/com/hazelcast/simulator/tests/map/domain/SerializableDomainObject.java

This test demonstrate impact of various serialization strategies on query performance. It has been extracted from a customer benchmarks.

SerializationStrategyTest added

---

simulator/pom.xml
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AbstractAsyncStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AsyncCacheStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AsyncMapStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/Streamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/StreamerFactory.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/SyncCacheStreamer.java
simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/SyncMapStreamer.java
simulator/src/test/java/com/hazelcast/simulator/worker/loadsupport/AsyncCacheStreamerTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/loadsupport/StreamerFactoryTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/loadsupport/SyncCacheStreamerTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/BatchingICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/CasICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/EntryProcessorICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/PerformanceICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/icache/StringICacheTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/IntByteMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/MapLongPerformanceTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/MapPredicateTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/PagingPredicateTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/SerializationStrategyTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/SqlPredicateTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/StringStringMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/queryresultsize/AbstractMapTest.java

Fixes #735
Streamer concept is independent on underlying storage.
It can be created on top of IMap and JCache.

Streamer implementation for JCache

---

dist/src/main/dist/simulator-tests/test.properties
tests/src/main/java/com/hazelcast/simulator/tests/concurrent/lock/LeaseLockTest.java

test for issue https://github.com/hazelcast/hazelcast/issues/6141

leaseLockTest

---

tests/src/main/java/com/hazelcast/simulator/tests/map/multivalues/MultiValueMapTest.java

A basic Simulator test for the querying on collections. 
This test is not working against the Hazelcast master (yet)

MultiValue Test added

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorUtils.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RemoteClient.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestPhaseListener.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestPhaseListenerContainer.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/WorkerParameters.java
simulator/src/main/java/com/hazelcast/simulator/protocol/connector/CoordinatorConnector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/ResponseType.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/OperationType.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/PhaseCompletedOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/MemberWorker.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunTestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorUtilsTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RemoteClientTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/WorkerParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/ProtocolUtil.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessorTest.java

Reversed phase completed logic to push states from workers instead of polling states from coordinator.

Refactored phase completed logic

---

tests/src/main/java/com/hazelcast/simulator/tests/map/MapPredicateTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/PagingPredicateTest.java

made some changes based on PagingPredicate Seek PRD

new versions of MapPredicateTest and PagingPredicateTest 

---

tests/src/main/java/com/hazelcast/simulator/tests/icache/ExpiryICacheTest.java

operate on a fixed well defined keyDomain with a known upper bound, which will not grow with the number of clients use

fix unconstrained put  in cause test used in HD off heap

---

tests/src/main/java/com/hazelcast/simulator/tests/helpers/KeyLocality.java
tests/src/main/java/com/hazelcast/simulator/tests/helpers/KeyUtils.java
tests/src/main/java/com/hazelcast/simulator/tests/map/IntByteMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/MapEntryProcessorTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/MapTransactionReadWriteTest.java
tests/src/main/java/com/hazelcast/simulator/tests/map/queryresultsize/AbstractMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/slow/SlowOperationMapTest.java
tests/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticTest.java
tests/src/test/java/com/hazelcast/simulator/tests/helpers/KeyUtilsTest.java

https://github.com/hazelcast/hazelcast-simulator/issues/812

Introduced SHARED keylocality

---

simulator/src/main/java/com/hazelcast/simulator/worker/loadsupport/AbstractAsyncStreamer.java

Replaced the logging thread in `AbstractAsyncStreamer` with a throttled logger (not exactly the same output, but better than no output and saves the additional thread).

Replaced the logging thread in AbstractAsyncStreamer

---

simulator/src/main/java/com/hazelcast/simulator/probes/Probe.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
simulator/src/main/java/com/hazelcast/simulator/probes/impl/ThroughputProbe.java
simulator/src/main/java/com/hazelcast/simulator/test/TestContainer.java
simulator/src/main/java/com/hazelcast/simulator/utils/AnnotationReflectionUtils.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitor.java
simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java
simulator/src/test/java/com/hazelcast/simulator/probes/impl/ThroughputProbeTest.java
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_BasicTest.java
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_InjectProbeTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/AnnotationReflectionUtilsTest.java

Renamed some methods in the probes

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStateContainer.java

It has been solved by removing the replacement of the queue. So the queue is only drained; never deleted. Therefor you
won't loose any items due to swapping out a queue.

Fixes #854

---

simulator/src/test/java/com/hazelcast/simulator/coordinator/PerformanceStateContainerTest.java

Removed a lot of complex state record from the setup method to the actual test method. Having the
update registrations done in the setup method, but the verification in the test method, makes it very
difficult to debug.

PerformanceStateContainerTest simplficiation

---

dist/src/main/dist/conf/worker.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerjvm/WorkerJvmLauncher.java

The files were copied into the worker directory after the java process started.

worker.sh has working profilers documented + fixed upload bug

---

simulator/src/main/java/com/hazelcast/simulator/test/TestCase.java
simulator/src/test/java/com/hazelcast/simulator/test/TestCaseTest.java

Property values with spaces are trimmed

---

simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java
simulator/src/test/java/com/hazelcast/simulator/worker/performance/WorkerPerformanceMonitorTest.java

No more latency prefix.
Extension is hgrm;which already implies latency histogram

Renamed latency files

---

dist/src/main/dist/conf/worker.sh

All hdr files are automatically converted to hgrm files

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java

THe code has been simplified by removing the CountDownLatch to wait for thread completion. Instead the Thread.join method is used.

TestCaseRunner wait for test completion simplification

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureContainer.java

After 25 critical and 25 non critical, it will stop displaying additional failures.
They are being written to file.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/899

The Coordinator console limits number of exceptions thrown

---

simulator/src/main/java/com/hazelcast/simulator/test/BaseThreadState.java
simulator/src/main/java/com/hazelcast/simulator/worker/TimeStepModel.java
simulator/src/main/java/com/hazelcast/simulator/worker/TimeStepRunner.java
simulator/src/main/java/com/hazelcast/simulator/worker/TimeStepRunnerCodeGenerator.java
simulator/src/main/resources/TimeStepRunner.ftl
simulator/src/test/java/com/hazelcast/simulator/test/TestContainer_TimeStepTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/TimeStepModel_IllegalTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/TimeStepRunStrategyIntegrationTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AtomicLongTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/AddRemoveListenerICacheTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/ReadWriteICacheTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/StringICacheTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/IntByteMapTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/MapEntryProcessorTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/MapLockTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/MapLongPerformanceTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/MapPutAllTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/MapRaceTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/SerializationStrategyTest.java
tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/StringStringMapTest.java

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/931

Renamed ThreadContext to ThreadState

---

simulator/src/main/java/com/hazelcast/simulator/worker/RunWithWorkersRunStrategy.java
simulator/src/main/java/com/hazelcast/simulator/worker/TimeStepRunStrategy.java

The problems was that the workers were created after the test is marked as running and
this can lead to the performance monitor not seeing the probes since the workers could cause the probes to be created later.
This leads to spurious test failures and in production it leads to NPE in performance monitor after which no more performance updates are send.

Fixes issues that probes are created too late

---

tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/MapTransactionReadWriteTest.java

Also fixed bug in get since it did a put instead

Converted MapTransactionTest to timestep approach

---

dist/pom.xml
dist/src/main/config/build-distribution-archive.xml
pom.xml
simulator/src/main/java/com/hazelcast/simulator/utils/BuildInfoUtils.java
tests/tests-hz37/pom.xml
tests/tests-hz38/pom.xml
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/MemberWriteHandlerFactory.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/MockIOService.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/NetworkTest.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/PayloadUtils.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/RequestFuture.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/TaggingPacketWriteHandler.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/TaggingWriteHandlerFactory.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/network/WriteHandlerFactory.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticBackupOperation.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticOperation.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticSerializableFactory.java
tests/tests-hz38/src/main/java/com/hazelcast/simulator/tests/synthetic/SyntheticTest.java

* Switched Simulator to Hazelcast version 3.8-SNAPSHOT
* Added new test module for Hazelcast version 3.7

Switched to Hazelcast version 3.8-SNAPSHOT

---

simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/test/java/com/hazelcast/simulator/common/SimulatorPropertiesTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java

This can be realized using simulator properties override if needed.

Removed --git setting from coordinator cli

---

dist/src/main/dist/conf/install-hazelcast-support.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/InstallVendorTask.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/ComponentRegistry.java
simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java

This is first part for interactive Coordinator
Also fixes issue on osx with creating a tmp dir
Fixed checkstyle issue

Pulled out InstallVendorTask

---

simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessSettings.java
simulator/src/main/java/com/hazelcast/simulator/cluster/AgentWorkerLayout.java
simulator/src/main/java/com/hazelcast/simulator/cluster/ClusterUtils.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/WorkerParameters.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/WorkerParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/operation/OperationCodecTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/CoordinatorRemoteControllerProcessorTest.java

Decoupled from HZ and decoupled from internals

Worker settings decoupling

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java

was not used and leading to unwanted complexity

Removed refreshJVM setting

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

I have not seen any usage. So lets remove it to simplify.

Removed agent file configuration option

---

simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RemoteClientTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/StartWorkersTaskTest.java

; since they now always have a ru…nning thread; they can hog resources.. memory retention + consuming cpu.. + I have no ide of the pending ping messages are going to pile up

Tests are now closing remote clients

---

simulator/src/main/java/com/hazelcast/simulator/agent/Agent.java
simulator/src/main/java/com/hazelcast/simulator/agent/FailureSenderImpl.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/common/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/InitSessionOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/OperationType.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessor.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentCliTest.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/agent/FailureSenderImplTest.java
simulator/src/test/java/com/hazelcast/simulator/common/TestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorCliTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorParametersTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RemoteClientTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/RunTestSuiteTaskTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/operation/FailureOperationTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/processors/AgentOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/registry/ComponentRegistryTest.java

where everything is running.
Needed to introduce session on the agent.

TestSuite id isn't used anymore to determine the directory

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/WorkerParameters.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/AgentWorkerLayout.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/WorkerParametersTest.java

Requires for more flexibility e.g multivendor support

Introduced workerparameter environment for flexible argument passing

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/ClusterConfiguration.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/deployment/DeploymentPlan.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/deployment/DeploymentPlanTest.java

The code was very procedural. Most of the state passed is now pushed
into the DeploymentPlan.

DeploymentPlan cleanup: round 1

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java

Before this fix the DeploymentPlan starts with the smallest agent (good),
but then moves to the next agent to assign workers, no matter if that
agent is the one with the least amount of workers.
This fix makes sure that for every worker being assigned, always the agent
with the lowest numbers of workers is being picked.
This didn't use to be an issue since we didn't stop/start members, but
with the remote this will happen.

DeploymentPlan pick smallest agent

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/KillWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/RcKillWorkersOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/CoordinatorOperationProcessor.java

Add count to killing workers: fix #1138
Add version spec to kill workers: fix #1148
Add worker type to kill workers: fix #1140

Version kill worker improvements for the remote

---

dist/src/main/dist/bin/benchmark-report
simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollector.java
simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java
simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java

Added switch for raw time:
fix #1105
Added switch for svg graphics
fix #1160
Added switch for show aggregation only
fix #1161
Added fix for timestamps not set correctly
fix #1162
Added fix for cleaning up tmp files on osx

Benchmark report improvements

---

simulator/src/main/java/com/hazelcast/simulator/common/TestCase.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureCollector.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/FailureOperation.java
simulator/src/main/java/com/hazelcast/simulator/protocol/processors/WorkerOperationProcessor.java
simulator/src/main/java/com/hazelcast/simulator/protocol/registry/ComponentRegistry.java
simulator/src/test/java/com/hazelcast/simulator/agent/AgentSmokeTest.java
simulator/src/test/java/com/hazelcast/simulator/common/TestSuiteTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/FailureCollectorTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/operation/FailureOperationTest.java
simulator/src/test/java/com/hazelcast/simulator/protocol/registry/ComponentRegistryTest.java

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/1197
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/1167

Testid uniqueness

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java

Fixes #1172 exit code for coordinat-remote run in case of failure #1208

Exit code for coordinat-remote run

---

tests/tests-common/src/main/java/com/hazelcast/simulator/tests/queue/TxnQueueWithLockTest.java

Also the locks were extracted into fields. There is no good reason
the always get them from a Hazelcast instance.

Unlock in the outer finally block

---

simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java
simulator/src/test/java/com/hazelcast/simulator/wizard/WizardCliTest.java

fixes https://github.com/hazelcast/hazelcast-simulator/issues/1159

Used test file paths

---

tests/tests-common/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java

The idea behind the hot get is that certain gets will be hotter than
regular gets. This is required for e.g. near cache testing where you
want to control if you do a hot get or not.
Also made some minor cleanups

Added hotget to IntIntMapTest

---

dist/src/main/dist/jdk-install/jdk-openjdk-8-64.sh
dist/src/main/dist/jdk-install/jdk-support.sh

Added OpenJDK 8 support

---

pom.xml
simulator/pom.xml

fix https://github.com/hazelcast/hazelcast-simulator/issues/1266

Upgrade to jclouds 2.0

---

dist/src/main/dist/bin/benchmark-report.py

New engine is python based and better maintainable than the bash version

New reporting engine

---

simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
simulator/src/test/java/com/hazelcast/simulator/common/SimulatorPropertiesTest.java

Trims values from simulator.properties

---

simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
simulator/src/test/java/com/hazelcast/simulator/common/SimulatorPropertiesTest.java

When old property USER is used, give error

---

dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/jdk-install/jdk-ibm-6-64.sh
dist/src/main/dist/jdk-install/jdk-ibm-7-64.sh
dist/src/main/dist/jdk-install/jdk-ibm-8-64.sh
dist/src/main/dist/jdk-install/jdk-ibm-9-64.sh
dist/src/main/dist/jdk-install/jdk-openjdk-6-64.sh
dist/src/main/dist/jdk-install/jdk-openjdk-7-64.sh
dist/src/main/dist/jdk-install/jdk-openjdk-9-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-6-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-7-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-8-64.sh
dist/src/main/dist/jdk-install/jdk-oracle-9-64.sh
dist/src/main/dist/jdk-install/jdk-support.sh
dist/src/main/dist/jdk-install/jdk-zulu-7-64.sh
dist/src/main/dist/jdk-install/jdk-zulu-8-64.sh

These changes are made by donnerbart. Reapplying them

Fixed Java installation scripts

---

simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepModel.java

Improved message when total timestep probability exceeded

---

dist/src/main/dist/conf/init.sh
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

The `init.sh` script was not successfully executed when without a proper upload of the script file.

Fixed init.sh upload and execution

---

simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

Deletes the simulator directory before installing

---

simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/ProvisionerCli.java
simulator/src/main/java/com/hazelcast/simulator/utils/AgentUtils.java
simulator/src/main/java/com/hazelcast/simulator/utils/Bash.java
simulator/src/test/java/com/hazelcast/simulator/provisioner/ProvisionerCliTest.java
simulator/src/test/java/com/hazelcast/simulator/provisioner/ProvisionerTest.java
simulator/src/test/java/com/hazelcast/simulator/utils/AgentUtilsTest.java

Add sudokill option to provisioner

---

dist/src/main/dist/conf/provisioner-log4j.xml

Supress cipher logging

---

simulator/src/main/java/com/hazelcast/simulator/common/FailureType.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRunMonolith.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureCollector.java
simulator/src/main/java/com/hazelcast/simulator/protocol/operation/FailureOperation.java

Failure of worker creation doesn't lead to failure

---

simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java

due to JMS connection problem to broker because 'localhost' is used instead
of the internal ip address.

Worker not starting

---

simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/AgentUtils.java
simulator/src/main/java/com/hazelcast/simulator/utils/CloudProviderUtils.java

Fixes harakri problem

---

simulator/src/main/java/com/hazelcast/simulator/test/AbstractTest.java
simulator/src/main/java/com/hazelcast/simulator/test/annotations/InjectVendor.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TestContainer_InjectHazelcastInstanceTest.java

Replacement for the InjectHazelcastInstance.
Needed for future integration for other vendors

InjectVendor annotation

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/TerminateWorkersTask.java
simulator/src/main/java/com/hazelcast/simulator/worker/WorkerOperationProcessor.java
simulator/src/test/java/com/hazelcast/simulator/StubPromise.java
simulator/src/test/java/com/hazelcast/simulator/worker/ScriptExecutorTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/WorkerOperationProcessorTest.java
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TestManagerTest.java

problem is that the exception stacktrace is logged multiple times
which is ugly in the log.

Fixed logging issue on worker

---

simulator/src/main/java/com/hazelcast/simulator/protocol/Server.java

In case of a processing failure, the server loop ended.

Server loop ending

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/vendors/HazelcastDriver.java
simulator/src/main/java/com/hazelcast/simulator/vendors/VendorDriver.java
simulator/src/test/java/com/hazelcast/simulator/vendors/HazelcastDriverTest.java

Licencekey cleanup for HazelcastDriver

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunMonolithTest.java

The problem was that not enough workers were created due to the
WorkerParmeter cleanup.

Fix DeploymentPlan bug

---

dist/src/main/dist/conf/agent_ssh_check.sh
dist/src/main/dist/conf/agent_start.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/AgentUtils.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/utils/BashCommand.java
simulator/src/test/java/com/hazelcast/simulator/provisioner/ProvisionerTest.java

fix https://github.com/hazelcast/hazelcast-simulator/issues/1345
fix https://github.com/hazelcast/hazelcast-simulator/issues/1335

Agent ssh check

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java
simulator/src/main/java/com/hazelcast/simulator/vendors/HazelcastDriver.java
simulator/src/main/java/com/hazelcast/simulator/vendors/IgniteDriver.java
simulator/src/main/java/com/hazelcast/simulator/vendors/VendorDriver.java
simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java

Driver noise fix

---

simulator/src/main/java/com/hazelcast/simulator/vendors/HazelcastDriver.java
simulator/src/main/java/com/hazelcast/simulator/vendors/IgniteDriver.java
simulator/src/main/java/com/hazelcast/simulator/vendors/VendorDriver.java

To log per worker type what has been loaded.

Minor vendor logging improvement

---

README.md
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/JitterThread.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java

Added the jitter thread

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/DeploymentPlan.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/FailureCollector.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/registry/AgentData.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/registry/ComponentRegistry.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/ArtifactCleanTask.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/RunTestSuiteTask.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/NodeMetadataPredicate.java
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/vendors/HazelcastDriver.java
simulator/src/main/java/com/hazelcast/simulator/vendors/IgniteDriver.java
simulator/src/main/java/com/hazelcast/simulator/wizard/Wizard.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRunMonolithTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/DeploymentPlanTest.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/tasks/StartWorkersTaskTest.java
simulator/src/test/java/com/hazelcast/simulator/vendors/StubVendorDriver.java

DeploymentPlan cleanup

---

dist/src/main/dist/bin/agent-ssh
dist/src/main/dist/bin/benchmark-report
dist/src/main/dist/conf/agent-ssh-log4j.xml
dist/src/main/dist/conf/agent_ssh_check.sh
simulator/src/main/java/com/hazelcast/simulator/agent/AgentsSshCli.java
simulator/src/main/java/com/hazelcast/simulator/utils/BashCommand.java

fix #1355 
Also included check to see which agents are alive.

Added tool for executing commands on all agents

---

simulator/src/main/java/com/hazelcast/simulator/protocol/core/AddressLevel.java
simulator/src/main/java/com/hazelcast/simulator/protocol/core/SimulatorAddress.java

Removed remote address level since not used

---

simulator/src/main/java/com/hazelcast/simulator/utils/PropertyBindingSupport.java
simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/PropertyBindingTest.java

fix #1478 problem with underscores in PropertyBinding

---

dist/src/main/dist/conf/worker.sh
dist/src/main/dist/conf/worker.sh_flamegraphs_perf
simulator/src/main/java/com/hazelcast/simulator/vendors/HazelcastDriver.java

HazelcastDriver sets Hazelcast log4j sys property

---

dist/pom.xml
dist/src/main/config/build-distribution-archive.xml
dist/src/main/dist/conf/agent_online_check.sh
dist/src/main/dist/conf/agent_shutdown.sh
dist/src/main/dist/conf/agent_start.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/IgniteTest.java
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/cache/CacheTest.java
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/concurrent/AtomicLongTest.java

Also some minor logging changes
fix https://github.com/hazelcast/hazelcast-simulator/issues/1510

Resolves various ignite integration problems

---

tests/tests-common/src/main/java/com/hazelcast/simulator/tests/icache/MangleICacheTest.java

[BACKPORT] Remove CachingProvider.close timestep from MangleICacheTest

---

dist/src/main/dist/bin/coordinator
simulator/pom.xml
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/vendors/VendorDriver.java
simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
tests/tests-ignite/pom.xml
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/IgniteDriver.java
tests/tests-ignite/src/test/java/com/hazelcast/simulator/ignite/IgniteDriverTest.java

Moved IgniteDriver into Ignite module

---

dist/src/main/dist/conf/install-simulator.sh
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
simulator/src/main/java/com/hazelcast/simulator/utils/Bash.java

No point in doing bash programming in Java.
fix https://github.com/hazelcast/hazelcast-simulator/issues/1403

Simulator installation is moved to bash script

---

dist/src/main/dist/conf/aws-ec2_provision.sh
simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java

Fix #1519 scale doesn't install simulator/java

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/cache/LongStringCacheTest.java
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/cache/LongStringCacheTest.java
tests/tests-infinispan/src/main/java/com/hazelcast/simulator/infinispan/cache/LongStringCacheTest.java

Added a LongStringCacheTest for hz/ignite/infispan

---

dist/src/main/dist/conf/install-hazelcast-support.sh
dist/src/main/dist/conf/upload.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteImpl.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/InstallUploadDirTask.java
simulator/src/test/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteImplTest.java

Fixes local upload problems

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/DownloadTask.java

Added session id to download option

---

dist/src/main/dist/conf/download.sh
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

Filters out the 'upload' directory from downloading.

---

dist/src/main/dist/conf/install-hazelcast.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java

Fixed classpath issues for boot

---

simulator-boot/src/main/java/com/hazelcast/simulator/boot/Options.java
simulator-boot/src/main/java/com/hazelcast/simulator/boot/Runner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestCaseRunner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/TestSuite.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/RunTestSuiteTask.java

Fixes warmup not being picked up for boot

---

simulator-boot/src/main/java/com/hazelcast/simulator/boot/OptionsBuilder.java
simulator-boot/src/main/java/com/hazelcast/simulator/boot/Runner.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/DownloadTask.java

Boot: Fixes test termination issues

---

simulator/src/main/java/com/hazelcast/simulator/agent/AgentsSshCli.java

Added option to execute bash command on specific agent

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/icache/IntByteICacheTest.java

This is a basic implementation of the cache based test supporting async operations. I'm thinking whether we should handle the exceptions differently, WDYT @pveentjer ?

IntByte cache based test

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/icache/helpers/CacheUtils.java

propertiesByInstanceItself doesn't exist in 3.6.

Fixes CacheUtils HZ 3.6 compatibility problem

---

dist/src/main/dist/conf/aws-ec2_provision.sh

Directories are not correctly 'configured in SELinus. So SSL fails without any clue about why it goes wrong (great work!)
fix https://github.com/hazelcast/hazelcast-simulator/issues/1651

Fixed ssh problem with RHEL/SELinux

---

simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorRemoteCli.java

So these are removed since it isn't valid.

The coordinatorRemoteCli has some unwanted --command documentation

---

dist/src/main/dist/conf/ignite.xml
dist/src/main/dist/examples/run_with_iterations.sh
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessLauncher.java
simulator/src/main/java/com/hazelcast/simulator/agent/workerprocess/WorkerProcessManager.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorParameters.java
simulator/src/main/java/com/hazelcast/simulator/utils/FileUtils.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/concurrent/AtomicLongTest.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/concurrent/atomiclong/AtomicLongTest.java
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/IgniteDriver.java
tests/tests-ignite/src/main/java/com/hazelcast/simulator/ignite/cache/CacheTest.java

Added support for iterative runs

---

dist/src/main/dist/jdk-install/jdk-zulu-8-64.sh

Upgraded zulu 8 support to latest

---

dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/jdk-install/jdk-zulu-9-64.sh

Added zulu 9 support

---

dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/jdk-install/jdk-zulu-10-64.sh

Added Zulu 10 support

---

dist/src/main/dist/conf/simulator.properties
dist/src/main/dist/jdk-install/jdk-openjdk-10-64.sh

Added OpenJDK 10 support

---

dist/src/main/dist/jdk-install/jdk-openjdk-8-64.sh

Fixes the broken OpenJDK 8 installation

---

tests/tests-infinispan/pom.xml
tests/tests-infinispan/src/main/java/com/hazelcast/simulator/infinispan/InfinispanDriver.java

Upgraded Infinispan to 9.2.0-Final

---

simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java

a comma was missing in the header.

Fixes an issue in the SimulatorHistogramLogProcessor

---

dist/src/main/dist/examples/flamegraph_prepare.sh
tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/cache/ExternalizablePojo.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/cache/LongExternalizableCacheTest.java

Also added example script for flamegraph prepare
of ec2 (yum based) nodes.

Added an externalizable test

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/map/LongStringMapTest.java

LongStringMapTest now using streamer.

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/map/SqlPredicateTest.java

fix  problem with SqlPredicateTest

---

tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/ConnectDisconnectTest.java
tests/tests-jedis/src/main/java/com/hazelcast/simulator/jedis/JedisDriver.java
tests/tests-memcached/src/main/java/com/hazelcast/simulator/memcached/MemcachedDriver.java

also fixed some checkstyle issues on other tests

Added ConnectDisconnectTest

---

archetype/src/main/resources/archetype-resources/pom.xml
dist/src/main/dist/conf/hazelcast.xml
simulator/pom.xml
tests/tests-hz/pom.xml

Remove deprecated features

---

dist/src/main/dist/conf/install-hazelcast.sh
simulator/src/test/resources/client-hazelcast.xml

Updated the XSD version for the client-hazelcast.xml

Client jar isn't needed any longer

---

dist/src/main/dist/conf/hazelcast.xml
tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/HazelcastTest.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/map/LongStringMapTest.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/map/BackupExpirationMapTest.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/map/ExtractorMapTest.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/map/MapMaxSizeTest.java

Changes required after merging hazelcast/hazelcast#15592

Use EvictionConfig for IMap eviction configuration

---

dist/src/main/dist/conf/worker.sh_async_profiler

It should receive time in seconds, not in 2m.

Fixed isue in async worker template script

---

simulator/src/main/java/com/hazelcast/simulator/agent/AgentsSshCli.java
simulator/src/main/java/com/hazelcast/simulator/common/AgentsFile.java
simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java
simulator/src/main/java/com/hazelcast/simulator/wizard/Wizard.java
tests/tests-hz/src/main/java/com/hazelcast/simulator/hz/map/LongStringMapTest.java

This way you can share the same agents.txt file with many working
directories.

agents.txt file looked up file tree.

---

dist/src/main/dist/conf/simulator.properties

Upgraded AMI

---

dist/src/main/dist/conf/init_report_files.sh
pom.xml
simulator/src/main/java/com/hazelcast/simulator/utils/HistogramTrimmer.java
simulator/src/main/java/com/hazelcast/simulator/utils/ReportCsv.java

fix https://github.com/hazelcast/hazelcast-simulator/issues/1806
Also upgraded to latest version of HdrHistogram

Fixes various report generator problems

---

archetype/src/main/resources/archetype-resources/workdir/client-hazelcast.xml
simulator/src/test/resources/client-hazelcast.xml

the cause were some old client configuration files.

Fixes CoordinatorTest

---

simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorUtils.java
simulator/src/test/java/com/hazelcast/simulator/utils/SimulatorUtilsTest.java

by removing code that isn't used
and needs no tests

Fixes test failure SimulatorUtils

---

drivers/driver-infinispan10/conf/infinispan.xml
drivers/driver-infinispan10/pom.xml

Unfortunately currently Infinispan10 is broken. Need to look into that.

Infinispan10 correct jar versions

---

dist/src/main/config/build-distribution-archive.xml
drivers/driver-lettuce5/pom.xml

Dependency fixes
Upgrade to newest version

Lettuce fixes

---

dist/src/main/dist/conf/aws-ec2_provision.sh
dist/src/main/dist/conf/simulator.properties

removal of peter key
removed some unused properties
removed some old todos

Various ec2 cleanups

---

dist/src/main/dist/conf/benchmark-report.py

Generates HTML benchmark report

HTML report generation

---

dist/src/main/dist/bin/benchmark-report

install yattag package using script.

install yattag package using script

---

dist/src/main/dist/conf/benchmark-report.py

Added support for multiple benchmarks in report.csv file

added multiple benchmarks support

---

dist/src/main/dist/bin/benchmark-report
dist/src/main/dist/conf/benchmark-report.py

Removed Yattag dependency hence no need of pip install now.
This will remove error scenarios where pip and python versions are incompatible.

removed yattag support

---

dist/src/main/dist/bin/agent
simulator/src/main/java/com/hazelcast/simulator/protocol/Server.java

I'm not sure why on some long tests there is an OOME on the agents.
Messages are accumulating but they should be immediately removed.
I have increased the max agent heap size + set ttl on the message.

Hopefully solved a agent OOME.

---

pom.xml

To version 5.0.4 which is the last release.

Upgraded jopt-simple

---

dist/src/main/dist/conf/upload-driver.sh
dist/src/main/dist/jdk-install/jdk_url.sh
drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/hz/map/LongByteArrayMapTest.java
drivers/driver-hazelcast3/src/main/java/com/hazelcast/simulator/hz/map/LongStringMapTest.java

Restores the pipelined get tests in hz 3.x
Minor layout in upload driver and jdk_url

Minor fixes

---

dist/src/main/dist/conf/install-simulator.sh
drivers/driver-infinispan10/src/main/java/com/hazelcast/simulator/infinispan10/cache/LongLongCacheTest.java
drivers/driver-infinispan10/src/main/java/com/hazelcast/simulator/infinispan10/cache/LongStringCacheTest.java
drivers/driver-infinispan11/src/main/java/com/hazelcast/simulator/infinispan11/cache/LongLongCacheTest.java
drivers/driver-infinispan11/src/main/java/com/hazelcast/simulator/infinispan11/cache/LongStringCacheTest.java
drivers/driver-infinispan9/src/main/java/com/hazelcast/simulator/infinispan9/cache/LongLongCacheTest.java
drivers/driver-infinispan9/src/main/java/com/hazelcast/simulator/infinispan9/cache/LongStringCacheTest.java
simulator/src/main/java/com/hazelcast/simulator/utils/ReportCsv.java

1: report csv generated has a bug that sometimes it didn't add all percentiles
fix https://github.com/hazelcast/hazelcast-simulator/issues/1916
2: when installing simulator, the directory is removed on the remote first.
fix https://github.com/hazelcast/hazelcast-simulator/issues/1914
3: Infinspan documentation improvement regarding put behavior.

Various fixes

---

simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunner.java
simulator/src/main/resources/TimeStepRunner.ftl
simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TestContainer_TimeStepReturnTypesTest.java

So the return values of timestep methods are stored in an
atomic per thread using lazySet. This should be cheap enough
for our purposes.

Added protection deadcode elimination

---

simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepRunner.java
simulator/src/main/resources/TimeStepRunner.ftl

This prevents starting up workers because the class
isn't available.

Removed dep on guave AtomicDouble

---

drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapEntryListenerTest.java

fix candidate for: https://hazelcast.slack.com/archives/C02MR6RLHPX/p1639414439070100
cc @olukas

Enhance test validation phase

---

src/simulator/perftest.py

Fix Hazelcast 5 EE driver name in the help message

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hz/map/LongStringMapInsertTest.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceMonitor.java
playbooks/install_simulator.yaml
src/simulator/perftest_report.py

Various minor improvements.
Added LongStringMapInsertTest
Added option to not destroy the map.
Upgraded dstat to PCP

Minor Improvements

---

conf/worker.sh_async_profiler
playbooks/install_async_profiler.yaml
src/inventory_cli.py

Use latest async profiler and replace svg extension with html

---

templates/hazelcast5-ec2/aws/main.tf
templates/hazelcast5-hd-ec2/aws/main.tf
templates/storage-ec2/aws/main.tf

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2019

Opens the TPC port ranges

---

README.md

I think it was a mistake. It should be username.

Change ssh command in README

---

bin/pps

This script can be configured with an interface to monitor.

Improved the packets per second monitoring script

---

src/perfregtest_cli.py
src/simulator/log.py
src/simulator/util.py

`shell_logged` method will also print with this change. This is useful to track progress.

`shell_logged` method will also print with this change.

---

README.md

While familiarising myself with the Simulator I noticed there were a few updates needed for the README documentation, so here they are!

Fix typos and generally update README.md

---

templates/elasticache-cluster/ansible.cfg
templates/hazelcast5-ec2/ansible.cfg
templates/hazelcast5-hd-ec2/ansible.cfg
templates/sql-ec2/ansible.cfg
templates/sql-lab/ansible.cfg
templates/storage-ec2/ansible.cfg

Supress Ansible python noise.

---

java/pom.xml

From very archaic, to slightly less archaic.
Updating to 5 would be ideal but isn't as simple as updating the version.

Bumping mockito version from 2 to 3.

---

java/pom.xml

Bumped maven compiler plugin version

---

templates/sql-prunability-ec2/ansible.cfg

Fix https://github.com/hazelcast/hazelcast-simulator/pull/2053

Added Ansible Python noise supression sql-prunability-ec2

---

java/pom.xml

Doesn't reflect who has contributed to Simulator.

Removed developers section from pom.

---

java/drivers/driver-lettuce6/pom.xml
java/drivers/driver-lettucecluster6/pom.xml

From 6.1.6.RELEASE to 6.2.6.RELEASE.

Bumped the lettuce driver version

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/BuildInfoUtils.java
java/simulator/src/test/java/com/hazelcast/simulator/worker/WorkerTest.java

Prevents the build from running correctly and we don't see any of the other build failures.
This test needs to be fixed at some point or just deleted.

Ignored broken WorkerTest

---

templates/hazelcast5-ec2/tests.yaml
templates/hazelcast5-hd-ec2/tests.yaml
templates/sql-ec2-tstore/tests.yaml
templates/sql-ec2/tests-predicates.yaml
templates/sql-ec2/tests-sql.yaml
templates/sql-prunability-ec2/tests.yaml
templates/storage-ec2/tests.yaml

Added the flags that by default need to be set to
get the best performance.

Added default --add-opens etc

---

java/drivers/driver-mongodb/pom.xml

Bumped the mongo driver version

---

build

Renamed empty_dir to make_empty_dir to better explain what the purpose is of the function.

Minor build cleanup

---

java/simulator/src/main/java/com/hazelcast/simulator/test/BaseThreadState.java
java/simulator/src/main/java/com/hazelcast/simulator/test/StopException.java
java/simulator/src/main/java/com/hazelcast/simulator/test/TestContext.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/AfterRun.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/BeforeRun.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/InjectDriver.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/InjectTestContext.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Prepare.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Run.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Setup.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/StartNanos.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Teardown.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/TimeStep.java
java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Verify.java

Most of the changes are reducing the documentation line length to 80.

Javadoc formatting.

---

README.md

Added explanation on various forms of testing and how it can be done using the simulator.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2077

Improved README.md: added performance testing section.

---

templates/elasticache-cluster/inventory_plan.yaml
templates/hazelcast5-ec2/inventory_plan.yaml
templates/hazelcast5-hd-ec2/inventory_plan.yaml
templates/sql-ec2/inventory_plan.yaml
templates/sql-prunability-ec2/inventory_plan.yaml
templates/storage-ec2/inventory_plan.yaml

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2104

Templates upgraded to ubuntu 22.04 LTS

---

conf/coordinator-log4j.xml
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hazelcast4plus/Hazelcast4PlusDriver.java
java/simulator/src/main/java/com/hazelcast/simulator/common/ProcessSuicideThread.java
java/simulator/src/main/java/com/hazelcast/simulator/coordinator/tasks/AgentsDownloadTask.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/BashCommand.java
java/simulator/src/main/java/com/hazelcast/simulator/utils/NativeUtils.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/ScriptExecutor.java
java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java
java/simulator/src/test/java/com/hazelcast/simulator/utils/BashCommandTest.java
src/upload_hazelcast_jars.py

So thrown an error and stop the execution of the test instead of silently ending.

Fixes problem when artifact not found.

---

playbooks/install_perf.yaml

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2140

Fix perf paranoid setting

---

src/simulator/perftest_report.py

Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2147

Fix non existing dir handling report tool.

---

src/simulator/perftest_report_common.py

Fix https://github.com/hazelcast/hazelcast-simulator/issues/2137

Fixes report generation utc problem.

---

java/simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java

When there are many agents (brokers), sequential connect is very time consuming.
Now it is done parallel, speeding up the process.
Fixes https://github.com/hazelcast/hazelcast-simulator/issues/2153

Parallel broker connect.

---

src/simulator/perftest_report.py

Minor cli argument handling cleanup.

Perftest report default argument for output.

---

src/simulator/perftest_report.py

The string 'report' needs to be part of the name of the file, otherwise simulator will not delete the directory.
So if someone would do:
`perftest report -o ~/FamilyPictures 23-10-2023_14-24-39`
Then the tool will fail if that directory already exists.
fixes: https://github.com/hazelcast/hazelcast-simulator/issues/2159

Protection unwanted report dir deletion.

---

templates/cp-ec2/.gitignore
templates/elasticache-cluster/.gitignore
templates/hazelcast5-ec2/.gitignore
templates/hazelcast5-hd-ec2/.gitignore
templates/sql-ec2-tstore/.gitignore
templates/sql-ec2/.gitignore
templates/sql-lab/.gitignore
templates/sql-prunability-ec2/.gitignore
templates/storage-ec2/.gitignore

Remove duplicate inventory.yaml and excluded the .jfr files.
Also all the .gitignore files are now identical.

Cleaned up .gitignore files in templates.

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/hz/map/AsyncLongStringMapTest.java

The existing LongStringMapTest (and many others) is unsuitable for generating high concurrency levels because threads are used for that. So for a concurrency of 1000, you would need 1000 threads.
The AsyncLongStringMapTest doesn't rely on threads to create concurrency and therefore can reach much higher concurrency levels without the threads' drawbacks.
For the time being, only get-operations are supported.

Added the AsyncLongStringMapTest

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/PagingPredicateTest.java

https://hazelcast.slack.com/archives/C066FTLVADV/p1702974018697879?thread_ts=1702970293.559929&cid=C066FTLVADV

Use public API for `PagingPredicate` creation

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/cp/IAtomicReferenceTest.java

So instead of having just a single AtomicReference, you can now configure the number of AtomicReferences.
And instead of always using the default CPGroup, the number of CPGroups can be configured. If set to 0, the default CPGroup will be used and otherwise the AtomicReferences are spread over the CPGroups in round robin fashion.

IAtomicReferenceTest configurable ref count + cp groups

---

java/drivers/driver-lettuce6/pom.xml
java/drivers/driver-lettucecluster6/pom.xml

Upgraded Lettuce version

---

src/simulator/perftest_report_operations.py

fixes https://github.com/hazelcast/hazelcast-simulator/issues/2169
Before the fix, it took more than 15m (I eventually killed the benchmark because it took too much time). With the fix in place, it is reduced to 30s.

Fixes slow operations csv parsing.

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/TieredStoreMapTest.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/helpers/tasks/ClearTsDirectoryTask.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/helpers/tasks/GetHybridLogLengthTask.java
java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/helpers/tasks/GetMapConfigTask.java

This test will be included in release testing.
Used disk space by each member is between 15-20GB (for defaults) and compaction to ~15GB is visible (checked after 24h of run)
**Before merge, needs change in name used via reflection after: https://github.com/hazelcast/hazelcast-mono/pull/844/**

Add Tiered Store Map test for simulator release tests [HZ-1554]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/helpers/tasks/GetHybridLogLengthTask.java

Required due to: https://github.com/hazelcast/hazelcast-mono/pull/844/

Update GetHybridLogLengthTask method name to latest changes in HZ

---

java/drivers/driver-hazelcast4plus/conf/configure.py
java/simulator/src/main/java/com/hazelcast/simulator/common/SimulatorProperties.java
java/simulator/src/main/java/com/hazelcast/simulator/coordinator/CoordinatorCli.java

So we want to control how many node workers are created and it should not be automatically based on the number of nodes. Maybe there are 3 nodes and you don't want to have any passive workers like e.g. for Redis.

Better handling of node_workers property.

---

src/inventory_cli.py
src/simulator/driver.py
src/simulator/inventory_terraform.py
src/simulator/perftest.py
src/simulator/ssh.py
src/simulator/util.py

- Adds package manager/linux distribution util
- Collect output from ssh commands
- Adds load_balancer hosts/ count
- Inventory terraform can parse out arn/private ip from load balancers
- Ignore load balancers when installing java/simulator
- Add post_run step to driver

New redis drivers support and utils

---

desigining_driver.md

Added documentation for how to design a new driver.

Documentation driver architecture

---

src/simulator/util.py

'==' should be used for string comparison, not 'is'.

Fixed string comparison problem in util.py

---

src/inventory_cli.py
src/simulator/inventory_lab.py
templates/hazelcast5-lab/.gitignore
templates/hazelcast5-lab/README.md
templates/hazelcast5-lab/ansible.cfg
templates/hazelcast5-lab/client-hazelcast.xml
templates/hazelcast5-lab/hazelcast.xml
templates/hazelcast5-lab/inventory_plan.yaml
templates/hazelcast5-lab/setup
templates/hazelcast5-lab/tests.yaml

Update to simulator to allow generating inventory.yaml file for running tests on the perf lab machines, added a new template outlining the available config.

Add simulator template for perf lab [DEX-352]

---

java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongByteArrayMapTest.java
src/simulator/perftest_report_hdr.py

The benchmark is useful for testsing https://github.com/hazelcast/hazelcast-mono/pull/4438

Add IMap benchmark with entry processor updating all entries

---

.github/workflows/ci.yml

Enhanced the CI workflow with manual triggering capabilities and integrated debugging tools to improve troubleshooting of workflow failures. This adds the ability to manually run the CI pipeline and optionally start a tmate debugging session for interactive troubleshooting.

chore: Add manual workflow dispatch and debugging capabilities
